db.inventory.insertMany([
    {"brand":"Good Neighbor Pharmacy","sellerRef":"Buzzshare","quantity":86,"unitPrice":32},
    {"brand":"Aveeno","sellerRef":"Latz","quantity":39,"unitPrice":57},
    {"brand":"CC Cream Daily Correct Broad Spectrum SPF 40 Sunscreen","sellerRef":"Riffwire","quantity":28,"unitPrice":23},
    {"brand":"ESZOPICLONE","sellerRef":"JumpXS","quantity":61,"unitPrice":7},
    {"brand":"Ginsamin Power","sellerRef":"Voonix","quantity":26,"unitPrice":12},
    {"brand":"Acid Reducer","sellerRef":"Teklist","quantity":39,"unitPrice":65},
    {"brand":"BHI Flu Plus","sellerRef":"Ozu","quantity":71,"unitPrice":61},
    {"brand":"nicotine","sellerRef":"Yakitri","quantity":18,"unitPrice":92},
    {"brand":"CENTURY 21 HEAVY METAL DETOX","sellerRef":"Devpulse","quantity":51,"unitPrice":39},
    {"brand":"Bull Frog Water Armor Super 40","sellerRef":"Yabox","quantity":9,"unitPrice":4},
    {"brand":"Common Sagebrush","sellerRef":"Thoughtbeat","quantity":71,"unitPrice":100},
    {"brand":"Theophylline","sellerRef":"Podcat","quantity":46,"unitPrice":89},
    {"brand":"Morphine Sulfate","sellerRef":"Wikido","quantity":11,"unitPrice":65},
    {"brand":"Mountain Cedar","sellerRef":"Voonte","quantity":26,"unitPrice":93},
    {"brand":"Instant Hand Sanitizer - Cocoa Butter","sellerRef":"Browsebug","quantity":48,"unitPrice":17},
    {"brand":"Sinus Congestion and Pain","sellerRef":"Quimba","quantity":96,"unitPrice":53},
    {"brand":"TMC-A Anti Hairloss","sellerRef":"Thoughtbridge","quantity":100,"unitPrice":88},
    {"brand":"Homeopathic Periodontal Gum Relief Formula","sellerRef":"Browsetype","quantity":50,"unitPrice":43},
    {"brand":"Hydroxyzine Hydrochloride","sellerRef":"Yadel","quantity":22,"unitPrice":72},
    {"brand":"Heavy Duty Hand Cleaner","sellerRef":"Oloo","quantity":26,"unitPrice":62},
    {"brand":"LBEL NATURAL FINISH MOISTURIZING FOUNDATION SPF 25","sellerRef":"Browsezoom","quantity":71,"unitPrice":41},
    {"brand":"Lac-Hydrin","sellerRef":"Thoughtbeat","quantity":46,"unitPrice":19},
    {"brand":"Topcare Nicotine","sellerRef":"Ozu","quantity":95,"unitPrice":71},
    {"brand":"Benazepril Hydrochloride","sellerRef":"Realmix","quantity":18,"unitPrice":61},
    {"brand":"Ready Foundation","sellerRef":"Skyba","quantity":76,"unitPrice":95},
    {"brand":"Oxygen","sellerRef":"Wordify","quantity":9,"unitPrice":47},
    {"brand":"Mexican Tea Pollen","sellerRef":"Agimba","quantity":66,"unitPrice":56},
    {"brand":"LBEL REPLENISHING FOUNDATION SPF 14","sellerRef":"Jayo","quantity":94,"unitPrice":35},
    {"brand":"health mart enema","sellerRef":"Yotz","quantity":25,"unitPrice":6},
    {"brand":"Apis Mell.","sellerRef":"Agivu","quantity":94,"unitPrice":53},
    {"brand":"Sertraline Hydrochloride","sellerRef":"Avamba","quantity":41,"unitPrice":12},
    {"brand":"Bull Frog Marathon Mist 36","sellerRef":"Kanoodle","quantity":5,"unitPrice":81},
    {"brand":"Olanzapine","sellerRef":"Wikizz","quantity":46,"unitPrice":3},
    {"brand":"Panadol","sellerRef":"Gevee","quantity":44,"unitPrice":45},
    {"brand":"Bug Bites - Itch Stopper","sellerRef":"Tanoodle","quantity":30,"unitPrice":14},
    {"brand":"Degree","sellerRef":"Browsezoom","quantity":43,"unitPrice":57},
    {"brand":"Bethanechol Chloride","sellerRef":"Innotype","quantity":79,"unitPrice":67},
    {"brand":"Bisacodyl Laxative","sellerRef":"Yambee","quantity":98,"unitPrice":28},
    {"brand":"Thiothixene","sellerRef":"Livetube","quantity":53,"unitPrice":40},
    {"brand":"METRONIDAZOLE","sellerRef":"Ozu","quantity":9,"unitPrice":9},
    {"brand":"Hazelnut","sellerRef":"Trilia","quantity":81,"unitPrice":52},
    {"brand":"Med Aid","sellerRef":"Zooveo","quantity":17,"unitPrice":69},
    {"brand":"health mart pain and fever","sellerRef":"Kwideo","quantity":93,"unitPrice":44},
    {"brand":"Sudafed","sellerRef":"Gabcube","quantity":56,"unitPrice":48},
    {"brand":"Omeprazole","sellerRef":"Npath","quantity":32,"unitPrice":43},
    {"brand":"LANOCREME HYDRATING","sellerRef":"Skyndu","quantity":98,"unitPrice":24},
    {"brand":"Neutrogena Wet Skin Swim Humidity Sweat","sellerRef":"Thoughtstorm","quantity":52,"unitPrice":78},
    {"brand":"Belladonna Alkaloids with Phenobartbital","sellerRef":"Linkbuzz","quantity":74,"unitPrice":67},
    {"brand":"Lorazepam","sellerRef":"Skalith","quantity":10,"unitPrice":77},
    {"brand":"Doxycycline","sellerRef":"Jabberstorm","quantity":13,"unitPrice":12},
    {"brand":"Diazepam","sellerRef":"Eimbee","quantity":78,"unitPrice":3},
    {"brand":"cold and cough","sellerRef":"Yodoo","quantity":69,"unitPrice":97},
    {"brand":"Exuviance CoverBlend Skin Caring Foundation","sellerRef":"Dablist","quantity":85,"unitPrice":90},
    {"brand":"AMLODIPINE BESYLATE","sellerRef":"Fivebridge","quantity":85,"unitPrice":77},
    {"brand":"LBEL EFFET PARFAIT Polvos Compactos de Larga Duracion para rostro FPS 15 /Long Lasting Compact SPF 15","sellerRef":"Browsedrive","quantity":40,"unitPrice":20},
    {"brand":"Seven","sellerRef":"Linklinks","quantity":2,"unitPrice":19},
    {"brand":"Diprivan","sellerRef":"Mudo","quantity":90,"unitPrice":33},
    {"brand":"Cold-EEZE","sellerRef":"Ailane","quantity":35,"unitPrice":89},
    {"brand":"Alphanate","sellerRef":"Pixope","quantity":82,"unitPrice":89},
    {"brand":"Rite Aid Original Strength Vagicaine","sellerRef":"Flipopia","quantity":50,"unitPrice":6},
    {"brand":"Rx Act Heartburn Relief","sellerRef":"Dabtype","quantity":79,"unitPrice":98},
    {"brand":"Fexofenadine HCl","sellerRef":"Vipe","quantity":13,"unitPrice":80},
    {"brand":"Hevert","sellerRef":"Aivee","quantity":6,"unitPrice":82},
    {"brand":"SEROQUEL","sellerRef":"Browseblab","quantity":68,"unitPrice":85},
    {"brand":"Agaricus Phosphorus","sellerRef":"Meedoo","quantity":62,"unitPrice":13},
    {"brand":"SKIN PROTECTANT","sellerRef":"Miboo","quantity":35,"unitPrice":57},
    {"brand":"URSODIOL","sellerRef":"Teklist","quantity":91,"unitPrice":11},
    {"brand":"CroupEx Sprinkles","sellerRef":"Browsebug","quantity":29,"unitPrice":47},
    {"brand":"Neutrogena Clinical Lifting Wrinkle Treatment System","sellerRef":"Quimm","quantity":2,"unitPrice":85},
    {"brand":"CVS Cold Hot Medicated","sellerRef":"Pixoboo","quantity":67,"unitPrice":14},
    {"brand":"Carbinoxamine Maleate","sellerRef":"Dabvine","quantity":56,"unitPrice":24},
    {"brand":"Omeprazole","sellerRef":"Fivebridge","quantity":30,"unitPrice":93},
    {"brand":"Flurazepam Hydrochloride","sellerRef":"Trupe","quantity":1,"unitPrice":35},
    {"brand":"Gas Relief","sellerRef":"InnoZ","quantity":1,"unitPrice":62},
    {"brand":"Cosopt","sellerRef":"Aivee","quantity":23,"unitPrice":36},
    {"brand":"A-METHAPRED","sellerRef":"Fivechat","quantity":91,"unitPrice":64},
    {"brand":"MegaFresh","sellerRef":"Gabcube","quantity":20,"unitPrice":85},
    {"brand":"Hand Armor","sellerRef":"Yambee","quantity":7,"unitPrice":100},
    {"brand":"PediaCare Childrens Plus Cough and Sore Throat","sellerRef":"Wikizz","quantity":60,"unitPrice":79},
    {"brand":"Pravastatin Sodium","sellerRef":"Tazz","quantity":48,"unitPrice":93},
    {"brand":"Rugby Nicotine Polacrilex Gum, Coated Mint Flavor","sellerRef":"Babblestorm","quantity":87,"unitPrice":19},
    {"brand":"Pramipexole Dihydrochloride","sellerRef":"Skinte","quantity":31,"unitPrice":55},
    {"brand":"Toms Whole Care Spearmint","sellerRef":"Oyoyo","quantity":69,"unitPrice":38},
    {"brand":"Metformin Hydrochloride","sellerRef":"Babbleopia","quantity":35,"unitPrice":68},
    {"brand":"AllergyEase Scent and Phenol","sellerRef":"Zooveo","quantity":30,"unitPrice":100},
    {"brand":"Eight Hour Cream Lip Protectant SPF 15","sellerRef":"Livetube","quantity":100,"unitPrice":1},
    {"brand":"STERILUBE OINTMENT","sellerRef":"Twitterbridge","quantity":86,"unitPrice":51},
    {"brand":"Sunmark Sinus and Cold D","sellerRef":"Kare","quantity":85,"unitPrice":50},
    {"brand":"DIDREX","sellerRef":"Browseblab","quantity":30,"unitPrice":52},
    {"brand":"BencoCaine Topical Anesthetic","sellerRef":"Jamia","quantity":19,"unitPrice":45},
    {"brand":"doxycycline hyclate","sellerRef":"Skajo","quantity":57,"unitPrice":9},
    {"brand":"Good Mood Enhancer","sellerRef":"Voonyx","quantity":15,"unitPrice":82},
    {"brand":"Citalopram","sellerRef":"Zoonoodle","quantity":88,"unitPrice":27},
    {"brand":"Ergotamine Tartrate and Caffeine","sellerRef":"Voonte","quantity":65,"unitPrice":47},
    {"brand":"good sense pain relief","sellerRef":"Brainbox","quantity":15,"unitPrice":67},
    {"brand":"08 Moisture Foundation SPF 15","sellerRef":"Thoughtbeat","quantity":70,"unitPrice":71},
    {"brand":"Chan Yat Hing She Kun Wool Lok Medicated Oil","sellerRef":"Jabbersphere","quantity":68,"unitPrice":100},
    {"brand":"Oxycodone Hydrochloride","sellerRef":"Linklinks","quantity":46,"unitPrice":5},
    {"brand":"TOPIRAMATE","sellerRef":"Tambee","quantity":11,"unitPrice":47},
    {"brand":"Mometasone Furoate","sellerRef":"Minyx","quantity":62,"unitPrice":79},
    {"brand":"Estradiol","sellerRef":"Babbleset","quantity":80,"unitPrice":20},
    {"brand":"PEACH SAKE SUN","sellerRef":"Realpoint","quantity":66,"unitPrice":10},
    {"brand":"Lip Smacker SPF 24 Lemon Lime Rush","sellerRef":"Photobug","quantity":85,"unitPrice":64},
    {"brand":"Flunisolide","sellerRef":"Abata","quantity":82,"unitPrice":91},
    {"brand":"up and up cold and sinus","sellerRef":"Trupe","quantity":75,"unitPrice":7},
    {"brand":"Childrens Pain Relief","sellerRef":"Camimbo","quantity":71,"unitPrice":47},
    {"brand":"Lustra-AF","sellerRef":"Youfeed","quantity":61,"unitPrice":15},
    {"brand":"Ofloxacin","sellerRef":"Wikido","quantity":26,"unitPrice":23},
    {"brand":"equaline","sellerRef":"Skinte","quantity":52,"unitPrice":100},
    {"brand":"Magnesium sulf. Bryonia","sellerRef":"Pixope","quantity":87,"unitPrice":94},
    {"brand":"MILK OF MAGNESIA MINT","sellerRef":"Jaxbean","quantity":81,"unitPrice":9},
    {"brand":"Quality Choice","sellerRef":"Vimbo","quantity":76,"unitPrice":63},
    {"brand":"ropinirole","sellerRef":"Zoomlounge","quantity":76,"unitPrice":39},
    {"brand":"Molds, Rusts and Smuts, Aspergillus fumigatus","sellerRef":"Skilith","quantity":40,"unitPrice":24},
    {"brand":"LBEL EFFET PARFAIT MINERAL NATURAL SKIN EFFECT MOUSSE FOUNDATION SPF 16","sellerRef":"Yakidoo","quantity":54,"unitPrice":85},
    {"brand":"Glipizide","sellerRef":"Twitterworks","quantity":61,"unitPrice":31},
    {"brand":"Sulfamethoxazole and Trimethoprim","sellerRef":"Skinte","quantity":29,"unitPrice":35},
    {"brand":"Metoprolol Tartrate","sellerRef":"Innojam","quantity":30,"unitPrice":88},
    {"brand":"Propranolol Hydrochloride","sellerRef":"Kwideo","quantity":19,"unitPrice":68},
    {"brand":"Neutrogena Ultimate Sport Sunblock","sellerRef":"Thoughtstorm","quantity":83,"unitPrice":8},
    {"brand":"EPIVIR","sellerRef":"Quire","quantity":31,"unitPrice":100},
    {"brand":"Fenofibrate","sellerRef":"Tavu","quantity":85,"unitPrice":34},
    {"brand":"Phenylephrine Hydrochloride","sellerRef":"Jazzy","quantity":96,"unitPrice":5},
    {"brand":"Paroxetine","sellerRef":"Voonix","quantity":29,"unitPrice":20},
    {"brand":"Publix Burn Relief","sellerRef":"Jetpulse","quantity":89,"unitPrice":10},
    {"brand":"Antioxidant Daily Protectant SPF 45","sellerRef":"Livefish","quantity":100,"unitPrice":66},
    {"brand":"Molds, Rusts and Smuts, Epicoccum nigrum","sellerRef":"Kwimbee","quantity":77,"unitPrice":68},
    {"brand":"PERFECTION LUMIERE VELVET","sellerRef":"Oyoyo","quantity":52,"unitPrice":70},
    {"brand":"Atenolol","sellerRef":"Photospace","quantity":25,"unitPrice":85},
    {"brand":"Perphenazine and Amitriptyline Hydrochloride","sellerRef":"Centizu","quantity":81,"unitPrice":81},
    {"brand":"MANGO BUTTER LIPSTICK","sellerRef":"Rooxo","quantity":28,"unitPrice":57},
    {"brand":"DESIPRAMINE HYDROCHLORIDE","sellerRef":"Eamia","quantity":100,"unitPrice":19},
    {"brand":"Lice MD","sellerRef":"Tanoodle","quantity":18,"unitPrice":52},
    {"brand":"PYRIDOSTIGMINE BROMIDE","sellerRef":"Oyondu","quantity":44,"unitPrice":67},
    {"brand":"flormar Foundation Sunscreen Broad Spectrum SPF 20 LF10 SAND BEIGE","sellerRef":"Flipstorm","quantity":95,"unitPrice":25},
    {"brand":"UNITHROID","sellerRef":"Plambee","quantity":41,"unitPrice":69},
    {"brand":"Carisoprodol","sellerRef":"Zoomdog","quantity":84,"unitPrice":38},
    {"brand":"Lac Caninum Kit Refill","sellerRef":"Yakidoo","quantity":77,"unitPrice":13},
    {"brand":"Diphenoxylate Hydrochloride and Atropine Sulfate","sellerRef":"Topicshots","quantity":4,"unitPrice":93},
    {"brand":"Paricalcitol","sellerRef":"Kwinu","quantity":88,"unitPrice":42},
    {"brand":"Valsartan and Hydrochlorothiazide","sellerRef":"Quamba","quantity":42,"unitPrice":4},
    {"brand":"Cold Head Congestion Daytime Non-Drowsy","sellerRef":"Innojam","quantity":27,"unitPrice":63},
    {"brand":"Ciclopirox","sellerRef":"Feedbug","quantity":90,"unitPrice":90},
    {"brand":"Oxcarbazepine","sellerRef":"Jayo","quantity":2,"unitPrice":51},
    {"brand":"Neptune E2 ANTISEPTIC HAND","sellerRef":"Twimm","quantity":20,"unitPrice":49},
    {"brand":"ATORVASTATIN CALCIUM","sellerRef":"Zoomdog","quantity":70,"unitPrice":8},
    {"brand":"Bethanechol Chloride","sellerRef":"Linkbridge","quantity":52,"unitPrice":70},
    {"brand":"METFORMIN HYDROCHLORIDE","sellerRef":"Fatz","quantity":31,"unitPrice":10},
    {"brand":"Quetiapine fumarate","sellerRef":"Roomm","quantity":58,"unitPrice":47},
    {"brand":"SOLIE EMULSION","sellerRef":"Roodel","quantity":46,"unitPrice":55},
    {"brand":"Bronzing Duo SPF 15 Mineral Compact Tint 01 Light","sellerRef":"Youopia","quantity":83,"unitPrice":31},
    {"brand":"rx act gas relief","sellerRef":"Vipe","quantity":66,"unitPrice":19},
    {"brand":"Black Walnut","sellerRef":"Voonyx","quantity":98,"unitPrice":5},
    {"brand":"Depakote","sellerRef":"Agivu","quantity":66,"unitPrice":10},
    {"brand":"ADVATE","sellerRef":"Oyoyo","quantity":8,"unitPrice":43},
    {"brand":"Walgreens","sellerRef":"Youbridge","quantity":58,"unitPrice":39},
    {"brand":"Bobbi Brown CC BROAD SPECTRUM SPF 25","sellerRef":"Tagchat","quantity":15,"unitPrice":91},
    {"brand":"NiteTime","sellerRef":"Pixonyx","quantity":36,"unitPrice":68},
    {"brand":"Octreotide Acetate","sellerRef":"Realbridge","quantity":55,"unitPrice":78},
    {"brand":"Aveeno Baby Organic Harvest Diaper Rash","sellerRef":"Cogilith","quantity":19,"unitPrice":49},
    {"brand":"LBEL COULEUR LUXE AMPLIFIER XP","sellerRef":"Photobean","quantity":100,"unitPrice":39},
    {"brand":"Amlodipine Besylate","sellerRef":"Tagtune","quantity":93,"unitPrice":47},
    {"brand":"Erythromycin-Benzoyl Peroxide","sellerRef":"Fanoodle","quantity":59,"unitPrice":33},
    {"brand":"Comfort Pac With Cyclobenzaprine","sellerRef":"Gevee","quantity":55,"unitPrice":16},
    {"brand":"Avandia","sellerRef":"Avaveo","quantity":48,"unitPrice":81},
    {"brand":"OXYBUTYNIN CHLORIDE","sellerRef":"Tagpad","quantity":78,"unitPrice":6},
    {"brand":"Acneclir","sellerRef":"Browsedrive","quantity":85,"unitPrice":13},
    {"brand":"Equisetum Silicea","sellerRef":"Abata","quantity":96,"unitPrice":21},
    {"brand":"Pure Finish Mineral Powder Foundation SPF 20 Pure Finish 1","sellerRef":"Devbug","quantity":48,"unitPrice":8},
    {"brand":"TAMSULOSIN HYDROCHLORIDE","sellerRef":"Janyx","quantity":89,"unitPrice":1},
    {"brand":"All Day Allergy","sellerRef":"Tagfeed","quantity":93,"unitPrice":40},
    {"brand":"Budesonide Inhalation","sellerRef":"Skaboo","quantity":22,"unitPrice":44},
    {"brand":"Furosemide","sellerRef":"Realpoint","quantity":23,"unitPrice":18},
    {"brand":"ESIKA 3-IN-1 PRO MAKE UP FOUNDATION SPF 20 BASE DE MAQUILLAJE PARA ROSTRO 3-EN-1 PRO FPS 20","sellerRef":"Rhybox","quantity":50,"unitPrice":43},
    {"brand":"Aspirin","sellerRef":"Quatz","quantity":70,"unitPrice":51},
    {"brand":"hair regrowth treatment","sellerRef":"Einti","quantity":13,"unitPrice":89},
    {"brand":"Oxygen","sellerRef":"Pixonyx","quantity":76,"unitPrice":22},
    {"brand":"Colgate Triple Action Original Mint Fluoride","sellerRef":"Meezzy","quantity":53,"unitPrice":24},
    {"brand":"Topcare Lansoprazole","sellerRef":"Jetpulse","quantity":83,"unitPrice":12},
    {"brand":"Wheat Smut","sellerRef":"Divanoodle","quantity":52,"unitPrice":56},
    {"brand":"House Dust Mite, Dermatophagoides pteronyssinus","sellerRef":"Yodo","quantity":17,"unitPrice":100},
    {"brand":"ESIKA","sellerRef":"Ooba","quantity":91,"unitPrice":98},
    {"brand":"Parasites","sellerRef":"Yombu","quantity":9,"unitPrice":85},
    {"brand":"Potassium Bicarbonate","sellerRef":"Trilia","quantity":93,"unitPrice":43},
    {"brand":"Loxapine","sellerRef":"Riffpath","quantity":29,"unitPrice":63},
    {"brand":"4 in 1 Pressed Mineral SPF 15 Deeper","sellerRef":"Skidoo","quantity":93,"unitPrice":34},
    {"brand":"Scarlight MD","sellerRef":"Brightbean","quantity":36,"unitPrice":64},
    {"brand":"AMOREPACIFIC","sellerRef":"Mudo","quantity":87,"unitPrice":77},
    {"brand":"health mart lansoprazole","sellerRef":"Aimbo","quantity":36,"unitPrice":91},
    {"brand":"AMOXICILLIN","sellerRef":"Plajo","quantity":8,"unitPrice":20},
    {"brand":"Dry Eye Test","sellerRef":"Voomm","quantity":60,"unitPrice":7},
    {"brand":"Diltiazem Hydrochloride","sellerRef":"Leenti","quantity":34,"unitPrice":38},
    {"brand":"ACETAMINOPHEN AND CODEINE PHOSPHATE","sellerRef":"Npath","quantity":86,"unitPrice":36},
    {"brand":"Clonazepam","sellerRef":"Eabox","quantity":28,"unitPrice":5},
    {"brand":"Lancome Paris Renergie Lift Volumetry","sellerRef":"Wikizz","quantity":66,"unitPrice":89},
    {"brand":"RAY DOL","sellerRef":"Fivespan","quantity":97,"unitPrice":93},
    {"brand":"TRAMADOL HYDROCHLORIDE","sellerRef":"Photospace","quantity":10,"unitPrice":96},
    {"brand":"MDSolarSciences SPF40 Mineral Screen","sellerRef":"Skipfire","quantity":7,"unitPrice":62},
    {"brand":"Paroxetine","sellerRef":"Brainverse","quantity":85,"unitPrice":81},
    {"brand":"Privet","sellerRef":"Kimia","quantity":33,"unitPrice":73},
    {"brand":"Aureobasidium pullulans","sellerRef":"Yotz","quantity":33,"unitPrice":39},
    {"brand":"Reef Safe SPF 45","sellerRef":"Kaymbo","quantity":15,"unitPrice":55},
    {"brand":"Estradiol","sellerRef":"Buzzshare","quantity":88,"unitPrice":18},
    {"brand":"Naproxen","sellerRef":"Jazzy","quantity":56,"unitPrice":48},
    {"brand":"Medium Expert Finish Makeup Makeup Broad Spectrum SPF 25","sellerRef":"Aibox","quantity":86,"unitPrice":40},
    {"brand":"Furosemide","sellerRef":"Shufflebeat","quantity":29,"unitPrice":36},
    {"brand":"ROBAXIN","sellerRef":"Jabberbean","quantity":67,"unitPrice":84},
    {"brand":"VANCOMYCIN HYDROCHLORIDE","sellerRef":"Youspan","quantity":32,"unitPrice":84},
    {"brand":"Nifedipine","sellerRef":"Oyoloo","quantity":31,"unitPrice":51},
    {"brand":"Edometriosis","sellerRef":"Brightdog","quantity":39,"unitPrice":59},
    {"brand":"Green Tea Antibacterial Hand Sanitizer","sellerRef":"Fatz","quantity":69,"unitPrice":38},
    {"brand":"ACYCLOVIR","sellerRef":"Skynoodle","quantity":1,"unitPrice":83},
    {"brand":"Riluzole","sellerRef":"Trilith","quantity":40,"unitPrice":55},
    {"brand":"Metformin Hydrochloride","sellerRef":"Quatz","quantity":55,"unitPrice":92},
    {"brand":"Neutrogena MoistureShine SPF20","sellerRef":"Ntags","quantity":67,"unitPrice":87},
    {"brand":"Metronidazole","sellerRef":"Oyoloo","quantity":90,"unitPrice":80},
    {"brand":"good neighbor pharmacy pain relief","sellerRef":"Trudeo","quantity":26,"unitPrice":19},
    {"brand":"Amoxicillin","sellerRef":"Zoombeat","quantity":20,"unitPrice":28},
    {"brand":"ACER NEGUNDO POLLEN","sellerRef":"Voolith","quantity":9,"unitPrice":35},
    {"brand":"HealthMart Mucus Relief FM","sellerRef":"Divape","quantity":52,"unitPrice":5},
    {"brand":"MAMONDE BRIGHTENING PACT 10HR N21","sellerRef":"Photolist","quantity":31,"unitPrice":6},
    {"brand":"CPDA-1","sellerRef":"Riffpath","quantity":32,"unitPrice":23},
    {"brand":"Pantoprazole Sodium","sellerRef":"Riffpath","quantity":31,"unitPrice":83},
    {"brand":"DESOGESTREL AND ETHINYL ESTRADIOL AND ETHINYL ESTRADIOL","sellerRef":"Bubbletube","quantity":13,"unitPrice":31},
    {"brand":"Covergirl Outlast Stay Fabulous 3in1 Foundation","sellerRef":"Abatz","quantity":1,"unitPrice":48},
    {"brand":"Clindamycin Hydrochloride","sellerRef":"Jabbercube","quantity":67,"unitPrice":36},
    {"brand":"Pacific Regional Allergies","sellerRef":"Youtags","quantity":36,"unitPrice":27},
    {"brand":"Indapamide","sellerRef":"Edgeify","quantity":54,"unitPrice":43},
    {"brand":"Amlodipine and Benazepril Hydrochloride","sellerRef":"Centidel","quantity":87,"unitPrice":23},
    {"brand":"Mirtazapine","sellerRef":"Thoughtbridge","quantity":97,"unitPrice":20},
    {"brand":"MORPHINE SULFATE","sellerRef":"Yakijo","quantity":49,"unitPrice":10},
    {"brand":"Fexofenadine Hydrochloride","sellerRef":"Skinder","quantity":41,"unitPrice":54},
    {"brand":"LBel","sellerRef":"Edgepulse","quantity":82,"unitPrice":88},
    {"brand":"SunScreen SPF30","sellerRef":"Camimbo","quantity":37,"unitPrice":16},
    {"brand":"Russian Thistle Pollen","sellerRef":"Quimm","quantity":17,"unitPrice":8},
    {"brand":"Melatonin Forte","sellerRef":"Camido","quantity":90,"unitPrice":22},
    {"brand":"TopCare","sellerRef":"Rhybox","quantity":46,"unitPrice":76},
    {"brand":"cetirizine hydrochloride","sellerRef":"Blognation","quantity":88,"unitPrice":4},
    {"brand":"Solu-Cortef","sellerRef":"Meetz","quantity":1,"unitPrice":35},
    {"brand":"Natural Advantage SPF 15 All Day Moisture with AHAs","sellerRef":"Katz","quantity":99,"unitPrice":63},
    {"brand":"Acetaminophen and Codeine Phosphate","sellerRef":"Rooxo","quantity":46,"unitPrice":77},
    {"brand":"Isosorbide Dinitrate","sellerRef":"Skippad","quantity":64,"unitPrice":57},
    {"brand":"LEVORPHANOL TARTRATE","sellerRef":"Avavee","quantity":21,"unitPrice":84},
    {"brand":"GOWOONSESANG EXPERT ACTIFIRM TM RECOVERY SUPER BLEMISH BASE","sellerRef":"Eare","quantity":13,"unitPrice":2},
    {"brand":"Carbo Vegetabilis Kit Refill","sellerRef":"Myworks","quantity":99,"unitPrice":92},
    {"brand":"Sodium Chloride","sellerRef":"Rhynyx","quantity":6,"unitPrice":42},
    {"brand":"equaline nicotine","sellerRef":"Topicstorm","quantity":8,"unitPrice":100},
    {"brand":"Lisinopril and Hydrochlorothiazide","sellerRef":"Meejo","quantity":9,"unitPrice":42},
    {"brand":"Luminous Goddess Aura BB","sellerRef":"Voonyx","quantity":88,"unitPrice":33},
    {"brand":"LOreal Paris Visible Lift Blur Foundation Broad Spectrum SPF 18 Sunscreen","sellerRef":"Zazio","quantity":2,"unitPrice":44},
    {"brand":"Childrens Acetaminophen","sellerRef":"Feedspan","quantity":73,"unitPrice":67},
    {"brand":"Advance White","sellerRef":"Fiveclub","quantity":47,"unitPrice":18},
    {"brand":"CALCAREA SULPHURICA","sellerRef":"Meedoo","quantity":92,"unitPrice":14},
    {"brand":"HCG Select Female Vitality Formula","sellerRef":"Meetz","quantity":25,"unitPrice":88},
    {"brand":"Cefprozil","sellerRef":"Topiclounge","quantity":37,"unitPrice":69},
    {"brand":"Milrinone Lactate","sellerRef":"Oyope","quantity":3,"unitPrice":81},
    {"brand":"RISPERIDONE","sellerRef":"Demivee","quantity":61,"unitPrice":78},
    {"brand":"Hydroxyzine Hydrochloride","sellerRef":"Realblab","quantity":45,"unitPrice":18},
    {"brand":"ADVANCED CELL BOOSTING EX DAY","sellerRef":"Devshare","quantity":38,"unitPrice":10},
    {"brand":"Amlodipine Besylate","sellerRef":"Twitterbeat","quantity":56,"unitPrice":68},
    {"brand":"Flu-less","sellerRef":"Yodel","quantity":9,"unitPrice":60},
    {"brand":"Low Strength Chewable Aspirin","sellerRef":"Skinix","quantity":75,"unitPrice":59},
    {"brand":"CVS COLD AND HOT MEDICATED XL","sellerRef":"Janyx","quantity":5,"unitPrice":29},
    {"brand":"Nifedipine","sellerRef":"Agimba","quantity":44,"unitPrice":52},
    {"brand":"Ear Ringing Symptom Formula","sellerRef":"Tagpad","quantity":69,"unitPrice":77},
    {"brand":"Glycopyrrolate","sellerRef":"Reallinks","quantity":50,"unitPrice":97},
    {"brand":"Parsley","sellerRef":"Zoovu","quantity":18,"unitPrice":48},
    {"brand":"Venlafaxine","sellerRef":"Kwideo","quantity":99,"unitPrice":58},
    {"brand":"Hazelnut","sellerRef":"Skinix","quantity":9,"unitPrice":2},
    {"brand":"Lab1796 High Blood Pressure Guard","sellerRef":"Eamia","quantity":4,"unitPrice":92},
    {"brand":"SAFEWAY","sellerRef":"Blogspan","quantity":83,"unitPrice":14},
    {"brand":"Tobramycin","sellerRef":"Jaloo","quantity":54,"unitPrice":40},
    {"brand":"Dove","sellerRef":"Omba","quantity":19,"unitPrice":63},
    {"brand":"TOPCARE","sellerRef":"Dabjam","quantity":65,"unitPrice":1},
    {"brand":"Bumetanide","sellerRef":"Agimba","quantity":14,"unitPrice":61},
    {"brand":"Stemphylium sarciniforms","sellerRef":"Feedmix","quantity":94,"unitPrice":36},
    {"brand":"WELLBUTRIN XL","sellerRef":"Talane","quantity":12,"unitPrice":38},
    {"brand":"Old Spice","sellerRef":"Feedbug","quantity":93,"unitPrice":17},
    {"brand":"Apricot","sellerRef":"Mynte","quantity":81,"unitPrice":9},
    {"brand":"Ropinirole","sellerRef":"Gabtune","quantity":70,"unitPrice":46},
    {"brand":"Theraproxen-90","sellerRef":"Vitz","quantity":14,"unitPrice":30},
    {"brand":"Secura Protective","sellerRef":"Meemm","quantity":79,"unitPrice":1},
    {"brand":"XtraCare Wet Wipes","sellerRef":"Meezzy","quantity":92,"unitPrice":87},
    {"brand":"Immature","sellerRef":"Yadel","quantity":92,"unitPrice":95},
    {"brand":"Phenytoin Sodium","sellerRef":"Wikibox","quantity":19,"unitPrice":22},
    {"brand":"RITE AID RENEWAL","sellerRef":"Realpoint","quantity":93,"unitPrice":78},
    {"brand":"Xenon","sellerRef":"Latz","quantity":66,"unitPrice":48},
    {"brand":"HOLYWOOD BEAUTY","sellerRef":"Zoombeat","quantity":82,"unitPrice":98},
    {"brand":"Witch Hazel","sellerRef":"Agimba","quantity":52,"unitPrice":35},
    {"brand":"Quercetin Phenolic","sellerRef":"Flashspan","quantity":74,"unitPrice":32},
    {"brand":"Cranberry","sellerRef":"Skalith","quantity":71,"unitPrice":42},
    {"brand":"SEBOBALANCE Spot Control","sellerRef":"Riffpedia","quantity":36,"unitPrice":68},
    {"brand":"TopCare Cough Relief Honey Lemon Flavor","sellerRef":"Voonder","quantity":96,"unitPrice":41},
    {"brand":"NAPROXEN","sellerRef":"Dynava","quantity":85,"unitPrice":39},
    {"brand":"Rheumatism","sellerRef":"Kamba","quantity":25,"unitPrice":21},
    {"brand":"Norepinephrine Bitartrate","sellerRef":"Flipbug","quantity":78,"unitPrice":87},
    {"brand":"Lisinopril","sellerRef":"Meeveo","quantity":44,"unitPrice":52},
    {"brand":"Risperidone","sellerRef":"Browseblab","quantity":28,"unitPrice":51},
    {"brand":"Nifedipine","sellerRef":"Rhybox","quantity":28,"unitPrice":15},
    {"brand":"Hello","sellerRef":"Skinix","quantity":14,"unitPrice":41},
    {"brand":"VERELAN PM","sellerRef":"Feedmix","quantity":69,"unitPrice":91},
    {"brand":"Tension Headache Relief","sellerRef":"Dazzlesphere","quantity":7,"unitPrice":56},
    {"brand":"Venlafaxine Hydrochloride","sellerRef":"Voonder","quantity":56,"unitPrice":96},
    {"brand":"equate lice killing","sellerRef":"Feedfire","quantity":25,"unitPrice":4},
    {"brand":"Geodon","sellerRef":"Mymm","quantity":70,"unitPrice":48},
    {"brand":"Ibuprofen","sellerRef":"Yodo","quantity":4,"unitPrice":74},
    {"brand":"Venlafaxine","sellerRef":"Yodoo","quantity":1,"unitPrice":21},
    {"brand":"TAMSULOSIN HYDROCHLORIDE","sellerRef":"Skivee","quantity":49,"unitPrice":59},
    {"brand":"Intuniv","sellerRef":"Yata","quantity":9,"unitPrice":47},
    {"brand":"Furosemide","sellerRef":"Zooxo","quantity":35,"unitPrice":88},
    {"brand":"ATROPINE SULFATE","sellerRef":"Twitterworks","quantity":14,"unitPrice":95},
    {"brand":"Banana Boat Sport SPF 50","sellerRef":"Snaptags","quantity":15,"unitPrice":38},
    {"brand":"Nitrogen","sellerRef":"Voonyx","quantity":37,"unitPrice":83},
    {"brand":"ARSENICUM ALBUM","sellerRef":"Zoonoodle","quantity":62,"unitPrice":23},
    {"brand":"ADSOL Red Cell Preservation Solution System in Plastic Container (PL 146 Plastic)","sellerRef":"Ntag","quantity":94,"unitPrice":51},
    {"brand":"Minipress","sellerRef":"Photobean","quantity":14,"unitPrice":51},
    {"brand":"Heparin Sodium","sellerRef":"Thoughtbeat","quantity":44,"unitPrice":30},
    {"brand":"NU-COPD","sellerRef":"Abatz","quantity":16,"unitPrice":96},
    {"brand":"Fluconazole","sellerRef":"Kwilith","quantity":56,"unitPrice":28},
    {"brand":"Doxycycline Hyclate","sellerRef":"Browseblab","quantity":11,"unitPrice":38},
    {"brand":"Ortho-Nesic With Capsaicin","sellerRef":"Voolith","quantity":69,"unitPrice":12},
    {"brand":"Fluphenazine Hydrochloride","sellerRef":"Twitterbridge","quantity":64,"unitPrice":74},
    {"brand":"VFEND","sellerRef":"Ainyx","quantity":18,"unitPrice":37},
    {"brand":"Food Additives","sellerRef":"Mynte","quantity":100,"unitPrice":42},
    {"brand":"OXYGEN","sellerRef":"Twiyo","quantity":63,"unitPrice":62},
    {"brand":"ADVIL","sellerRef":"Aimbu","quantity":82,"unitPrice":34},
    {"brand":"Risperidone","sellerRef":"Skyble","quantity":78,"unitPrice":98},
    {"brand":"Neova Day Therapy","sellerRef":"Kimia","quantity":81,"unitPrice":45},
    {"brand":"DOCTORS CHOICE","sellerRef":"Plambee","quantity":58,"unitPrice":68},
    {"brand":"Salicylic Acid","sellerRef":"Rhycero","quantity":66,"unitPrice":49},
    {"brand":"equate Sugar Free Fiber Therapy Smooth Texture Orange Flavor","sellerRef":"Browsecat","quantity":85,"unitPrice":98},
    {"brand":"Day Time Cold Multi-Symptom Cool Blast","sellerRef":"Eayo","quantity":90,"unitPrice":14},
    {"brand":"night time","sellerRef":"Thoughtbridge","quantity":77,"unitPrice":38},
    {"brand":"Phendimetrazine Tartrate","sellerRef":"Vitz","quantity":96,"unitPrice":15},
    {"brand":"ULTIMATE AQUA BLANC PROTECTIVE","sellerRef":"Pixonyx","quantity":80,"unitPrice":18},
    {"brand":"Virus 2000","sellerRef":"Dynava","quantity":38,"unitPrice":63},
    {"brand":"Doxepin Hydrochloride","sellerRef":"BlogXS","quantity":41,"unitPrice":89},
    {"brand":"HAWAIIAN Tropic","sellerRef":"JumpXS","quantity":17,"unitPrice":21},
    {"brand":"Losartan Potassium","sellerRef":"Yadel","quantity":58,"unitPrice":58},
    {"brand":"LEVOTHYROXINE SODIUM","sellerRef":"Skyba","quantity":46,"unitPrice":60},
    {"brand":"Promethazine Hydrochloride","sellerRef":"Leenti","quantity":47,"unitPrice":58},
    {"brand":"GOLD CAVIAR BB","sellerRef":"Quire","quantity":10,"unitPrice":5},
    {"brand":"Cephalexin","sellerRef":"Zoovu","quantity":89,"unitPrice":13},
    {"brand":"Caverject","sellerRef":"Skyba","quantity":28,"unitPrice":47},
    {"brand":"Clopidogrel","sellerRef":"Feedbug","quantity":47,"unitPrice":66},
    {"brand":"Corn Pollen","sellerRef":"Kaymbo","quantity":95,"unitPrice":47},
    {"brand":"Daily Moisturizing","sellerRef":"Roombo","quantity":57,"unitPrice":44},
    {"brand":"Zovirax","sellerRef":"Vimbo","quantity":26,"unitPrice":75},
    {"brand":"ampicillin","sellerRef":"Kazu","quantity":30,"unitPrice":27},
    {"brand":"CounterAct","sellerRef":"Yakitri","quantity":33,"unitPrice":57},
    {"brand":"Bye Bye Diaper Rash","sellerRef":"Snaptags","quantity":6,"unitPrice":14},
    {"brand":"BUPROPION HYDROCHLORIDE","sellerRef":"Buzzster","quantity":93,"unitPrice":29},
    {"brand":"nasal","sellerRef":"Gevee","quantity":48,"unitPrice":82},
    {"brand":"Venlafaxine Hydrochloride","sellerRef":"Flashdog","quantity":7,"unitPrice":36},
    {"brand":"Goose Feathers","sellerRef":"Skipfire","quantity":93,"unitPrice":35},
    {"brand":"Famotidine","sellerRef":"Skyble","quantity":19,"unitPrice":17},
    {"brand":"nasal","sellerRef":"Zooxo","quantity":21,"unitPrice":49},
    {"brand":"Nucynta","sellerRef":"Eazzy","quantity":33,"unitPrice":10},
    {"brand":"Bacitracin Zinc and Polymyxin B Sulfate","sellerRef":"Twitternation","quantity":66,"unitPrice":14},
    {"brand":"aspirin","sellerRef":"Skyvu","quantity":34,"unitPrice":8},
    {"brand":"Honey Bee hymenoptera venom Venomil Maintenance","sellerRef":"Kimia","quantity":93,"unitPrice":86},
    {"brand":"Stay Awake","sellerRef":"Minyx","quantity":91,"unitPrice":61},
    {"brand":"aloevella","sellerRef":"Kwideo","quantity":9,"unitPrice":28},
    {"brand":"Acetaminophen 8 Hour","sellerRef":"Yombu","quantity":60,"unitPrice":100},
    {"brand":"Lidocaine","sellerRef":"Eamia","quantity":47,"unitPrice":40},
    {"brand":"Cefazolin","sellerRef":"Fiveclub","quantity":74,"unitPrice":50},
    {"brand":"Amitriptyline Hydrochloride","sellerRef":"Tagcat","quantity":49,"unitPrice":12},
    {"brand":"LUCENTIS","sellerRef":"Fivebridge","quantity":68,"unitPrice":1},
    {"brand":"Nadolol","sellerRef":"Demivee","quantity":16,"unitPrice":70},
    {"brand":"Metamucil","sellerRef":"Aibox","quantity":84,"unitPrice":14},
    {"brand":"benzoyl peroxide","sellerRef":"Dynazzy","quantity":71,"unitPrice":58},
    {"brand":"Badger SPF 35 All Season Face","sellerRef":"Yamia","quantity":79,"unitPrice":57},
    {"brand":"Burning Runny Nose","sellerRef":"Trunyx","quantity":78,"unitPrice":48},
    {"brand":"Povidone Iodine Impregnated","sellerRef":"Realfire","quantity":42,"unitPrice":17},
    {"brand":"Cardene IV","sellerRef":"Topicware","quantity":55,"unitPrice":47},
    {"brand":"Prazosin Hydrochloride","sellerRef":"Fivespan","quantity":96,"unitPrice":25},
    {"brand":"Gliadel","sellerRef":"Livetube","quantity":9,"unitPrice":3},
    {"brand":"Hog Epithelium","sellerRef":"Thoughtworks","quantity":2,"unitPrice":85},
    {"brand":"flormar REBORN BB SUNSCREEN BROAD SPECTRUM SPF 30 CP10 Classic Beige","sellerRef":"Tavu","quantity":51,"unitPrice":10},
    {"brand":"Amoxicillin","sellerRef":"Gigaclub","quantity":23,"unitPrice":4},
    {"brand":"Linkus Lozenges","sellerRef":"Edgewire","quantity":17,"unitPrice":95},
    {"brand":"Metaxalone","sellerRef":"Yodoo","quantity":35,"unitPrice":15},
    {"brand":"Tizanidine Hydrochloride","sellerRef":"Dabshots","quantity":90,"unitPrice":80},
    {"brand":"Propofol","sellerRef":"Demimbu","quantity":54,"unitPrice":96},
    {"brand":"Daily Moisturizing","sellerRef":"Aimbu","quantity":74,"unitPrice":26},
    {"brand":"Acyclovir","sellerRef":"Jaxworks","quantity":28,"unitPrice":52},
    {"brand":"Oat Smut","sellerRef":"Gabspot","quantity":33,"unitPrice":36},
    {"brand":"Clindamycin Hydrochloride","sellerRef":"Yadel","quantity":74,"unitPrice":23},
    {"brand":"Levaquin","sellerRef":"Skipfire","quantity":27,"unitPrice":9},
    {"brand":"FLAWLESS SKIN MAKEUP BROAD SPECTRUM SPF 15","sellerRef":"Cogidoo","quantity":67,"unitPrice":24},
    {"brand":"Desert Beige Always Stay-on Makeup SPF 15","sellerRef":"Mynte","quantity":22,"unitPrice":79},
    {"brand":"pain relief pm","sellerRef":"Centidel","quantity":72,"unitPrice":83},
    {"brand":"Metformin Hydrochloride","sellerRef":"Vinder","quantity":22,"unitPrice":31},
    {"brand":"Kogenate FS","sellerRef":"Browseblab","quantity":77,"unitPrice":35},
    {"brand":"Corn Pollen","sellerRef":"Innotype","quantity":90,"unitPrice":93},
    {"brand":"Anchor Foaming Hand Sanitizer","sellerRef":"Ooba","quantity":69,"unitPrice":17},
    {"brand":"INFANTS GAS AND COLIC RELIEF","sellerRef":"Npath","quantity":5,"unitPrice":19},
    {"brand":"Fire Ant","sellerRef":"Zoovu","quantity":27,"unitPrice":4},
    {"brand":"Infected Cuts and Punctures","sellerRef":"Quinu","quantity":43,"unitPrice":6},
    {"brand":"Hair Regrowth Treatment for Men","sellerRef":"Skyba","quantity":75,"unitPrice":75},
    {"brand":"Physical Anger","sellerRef":"Dynabox","quantity":40,"unitPrice":71},
    {"brand":"Naratriptan","sellerRef":"Linkbuzz","quantity":44,"unitPrice":54},
    {"brand":"Cartilago Quartz","sellerRef":"Pixope","quantity":51,"unitPrice":84},
    {"brand":"Metoprolol Tartrate","sellerRef":"Devcast","quantity":84,"unitPrice":4},
    {"brand":"ONDANSETRON","sellerRef":"Wikizz","quantity":3,"unitPrice":88},
    {"brand":"6 Liver","sellerRef":"Lazz","quantity":24,"unitPrice":35},
    {"brand":"theSafetyDirector aquapreserv","sellerRef":"Realblab","quantity":59,"unitPrice":28},
    {"brand":"Homeopathic Burn","sellerRef":"Snaptags","quantity":88,"unitPrice":44},
    {"brand":"Metformin Hydrochloride","sellerRef":"Skimia","quantity":13,"unitPrice":27},
    {"brand":"Famotidine","sellerRef":"Quatz","quantity":39,"unitPrice":67},
    {"brand":"Lisinopril and Hydrochlorothiazide","sellerRef":"Innotype","quantity":45,"unitPrice":71},
    {"brand":"Lisinopril and Hydrochlorothiazide","sellerRef":"Fivespan","quantity":57,"unitPrice":20},
    {"brand":"Sertraline Hydrochloride","sellerRef":"Blognation","quantity":95,"unitPrice":13},
    {"brand":"Lisinopril","sellerRef":"Photobug","quantity":62,"unitPrice":30},
    {"brand":"Family Wellness Hydrocortisone","sellerRef":"Skippad","quantity":58,"unitPrice":87},
    {"brand":"Colgate","sellerRef":"Thoughtbeat","quantity":57,"unitPrice":63},
    {"brand":"Glyburide and Metformin Hydrochloride","sellerRef":"Devcast","quantity":88,"unitPrice":52},
    {"brand":"Sandy Beige","sellerRef":"Jaloo","quantity":14,"unitPrice":37},
    {"brand":"Renewal Hydrating Healing","sellerRef":"Skipstorm","quantity":35,"unitPrice":40},
    {"brand":"Gonal-f","sellerRef":"Livefish","quantity":92,"unitPrice":81},
    {"brand":"Carduus Oxalis","sellerRef":"Cogibox","quantity":27,"unitPrice":88},
    {"brand":"Bay Leaf","sellerRef":"Muxo","quantity":16,"unitPrice":36},
    {"brand":"Green Guard First Aid Eye Wash","sellerRef":"Plajo","quantity":23,"unitPrice":20},
    {"brand":"FormuCare Ranitidine","sellerRef":"Flipopia","quantity":17,"unitPrice":8},
    {"brand":"Eczema","sellerRef":"Voolia","quantity":42,"unitPrice":35},
    {"brand":"BETAMETHASONE DIPROPIONATE","sellerRef":"Einti","quantity":94,"unitPrice":94},
    {"brand":"Equate Cleansing Pads","sellerRef":"Jamia","quantity":22,"unitPrice":35},
    {"brand":"Comfort Pac with Meloxicam","sellerRef":"Devpulse","quantity":26,"unitPrice":53},
    {"brand":"nasal decongestant","sellerRef":"Wikivu","quantity":23,"unitPrice":69},
    {"brand":"Oxygen","sellerRef":"Voomm","quantity":31,"unitPrice":87},
    {"brand":"HydrALAZINE Hydrochloride","sellerRef":"Trudeo","quantity":65,"unitPrice":86},
    {"brand":"Clonidine Hydrochloride","sellerRef":"Miboo","quantity":37,"unitPrice":70},
    {"brand":"PROPRANOLOL HYDROCHLORIDE","sellerRef":"Flipopia","quantity":69,"unitPrice":30},
    {"brand":"ziprasidone hydrochloride","sellerRef":"Twitterbridge","quantity":55,"unitPrice":11},
    {"brand":"Citalopram Hydrobromide","sellerRef":"Tavu","quantity":25,"unitPrice":32},
    {"brand":"Neosporin Eczema Essentials","sellerRef":"Zoomzone","quantity":81,"unitPrice":47},
    {"brand":"Cyclosporine","sellerRef":"Twitterbeat","quantity":17,"unitPrice":78},
    {"brand":"ROSACLEAR SYSTEM","sellerRef":"Demizz","quantity":36,"unitPrice":81},
    {"brand":"CONSTIPATION","sellerRef":"Edgewire","quantity":53,"unitPrice":80},
    {"brand":"Degree","sellerRef":"Centimia","quantity":24,"unitPrice":38},
    {"brand":"Neutrogena Nourishing Eye Quad","sellerRef":"Youbridge","quantity":8,"unitPrice":28},
    {"brand":"Toast Always color stay-on Makeup Broad Spectrum SPF 15","sellerRef":"Quaxo","quantity":19,"unitPrice":45},
    {"brand":"fondaparinux sodium","sellerRef":"Linkbridge","quantity":20,"unitPrice":10},
    {"brand":"Simvastatin","sellerRef":"Jayo","quantity":35,"unitPrice":39},
    {"brand":"MITIGARE","sellerRef":"Voomm","quantity":93,"unitPrice":52},
    {"brand":"Ileocecal Valve Support","sellerRef":"Livetube","quantity":71,"unitPrice":70},
    {"brand":"AIM","sellerRef":"Podcat","quantity":87,"unitPrice":11},
    {"brand":"Methotrexate","sellerRef":"Fadeo","quantity":35,"unitPrice":73},
    {"brand":"all day relief","sellerRef":"Gevee","quantity":28,"unitPrice":64},
    {"brand":"Propafenone","sellerRef":"Katz","quantity":45,"unitPrice":8},
    {"brand":"Androgel","sellerRef":"Twinte","quantity":62,"unitPrice":8},
    {"brand":"Meclizine Hydrochloride","sellerRef":"Jabberbean","quantity":69,"unitPrice":16},
    {"brand":"LBEL FILLING EFFECT FOUNDATION SPF 10","sellerRef":"Skipstorm","quantity":82,"unitPrice":66},
    {"brand":"tourist spf30","sellerRef":"Flashspan","quantity":22,"unitPrice":3},
    {"brand":"SAFEWAY","sellerRef":"BlogXS","quantity":66,"unitPrice":40},
    {"brand":"Benazepril Hydrochloride","sellerRef":"Gabtune","quantity":18,"unitPrice":94},
    {"brand":"risperidone","sellerRef":"Devpoint","quantity":84,"unitPrice":27},
    {"brand":"Arnica 10% First Aid","sellerRef":"Dabjam","quantity":18,"unitPrice":2},
    {"brand":"Cryptotox Combo","sellerRef":"Realfire","quantity":38,"unitPrice":53},
    {"brand":"Nostalgia","sellerRef":"Myworks","quantity":7,"unitPrice":44},
    {"brand":"simvastatin","sellerRef":"Buzzdog","quantity":18,"unitPrice":6},
    {"brand":"Antibacterial Foaming Hand","sellerRef":"Meemm","quantity":26,"unitPrice":100},
    {"brand":"SUMADAN XLT","sellerRef":"Quinu","quantity":13,"unitPrice":34},
    {"brand":"Instant Hand Sanitizer - Ice Clear","sellerRef":"Katz","quantity":22,"unitPrice":82},
    {"brand":"Mugwort","sellerRef":"Tanoodle","quantity":63,"unitPrice":93},
    {"brand":"Quik-Care","sellerRef":"Gigashots","quantity":90,"unitPrice":47},
    {"brand":"Vasopressin","sellerRef":"Rooxo","quantity":89,"unitPrice":98},
    {"brand":"Topcare childrens allergy","sellerRef":"Meejo","quantity":6,"unitPrice":63},
    {"brand":"Ziprasidone hydrochloride","sellerRef":"Wikibox","quantity":43,"unitPrice":11},
    {"brand":"Fondaparinux Sodium","sellerRef":"Riffpath","quantity":68,"unitPrice":94},
    {"brand":"Sulfamethoxazole and Trimethoprim","sellerRef":"Dabshots","quantity":89,"unitPrice":18},
    {"brand":"Luveris","sellerRef":"Youspan","quantity":8,"unitPrice":87},
    {"brand":"Coconut","sellerRef":"Gabspot","quantity":56,"unitPrice":11},
    {"brand":"antibiotic and pain relief","sellerRef":"Livetube","quantity":60,"unitPrice":18},
    {"brand":"smart sense pain relief","sellerRef":"Leenti","quantity":100,"unitPrice":85},
    {"brand":"Extra Strength Pain Reliever PM","sellerRef":"Skynoodle","quantity":18,"unitPrice":63},
    {"brand":"Accupril","sellerRef":"Tambee","quantity":91,"unitPrice":2},
    {"brand":"SHISEIDO SUNCARE ULTIMATE","sellerRef":"Meeveo","quantity":35,"unitPrice":2},
    {"brand":"ERY-TAB","sellerRef":"Rhynoodle","quantity":16,"unitPrice":90},
    {"brand":"Olanzapine","sellerRef":"Skajo","quantity":37,"unitPrice":38},
    {"brand":"Speed Stick","sellerRef":"Gigashots","quantity":62,"unitPrice":98},
    {"brand":"Anti-Bacterial Hand","sellerRef":"Tagchat","quantity":34,"unitPrice":23},
    {"brand":"Aspergillus flavus","sellerRef":"Topicware","quantity":69,"unitPrice":55},
    {"brand":"GoodSense","sellerRef":"Wikido","quantity":46,"unitPrice":68},
    {"brand":"Phenytoin Sodium","sellerRef":"Trudeo","quantity":4,"unitPrice":16},
    {"brand":"Horse Epithelium","sellerRef":"Mynte","quantity":98,"unitPrice":69},
    {"brand":"The Natural Dentist","sellerRef":"Skajo","quantity":78,"unitPrice":44},
    {"brand":"LBEL COULEUR LUXE AMPLIFIER XP","sellerRef":"Avaveo","quantity":25,"unitPrice":27},
    {"brand":"Hydroxyzine Hydrochloride","sellerRef":"Fliptune","quantity":43,"unitPrice":33},
    {"brand":"Trazodone Hydrochloride","sellerRef":"Linklinks","quantity":55,"unitPrice":4},
    {"brand":"Charley Horse","sellerRef":"Dabfeed","quantity":85,"unitPrice":14},
    {"brand":"Kleenex Foam Antibacterial Skin Cleanser","sellerRef":"Tavu","quantity":84,"unitPrice":5},
    {"brand":"lisinopril","sellerRef":"Zazio","quantity":68,"unitPrice":53},
    {"brand":"AHC Vital C Complex Mask","sellerRef":"Quimba","quantity":46,"unitPrice":13},
    {"brand":"NWI LUBRICATING","sellerRef":"Feedfish","quantity":85,"unitPrice":63},
    {"brand":"Ropinirole Hydrochloride","sellerRef":"Rhycero","quantity":61,"unitPrice":45},
    {"brand":"Losartan Potassium and Hydrochlorothiazide","sellerRef":"Mydeo","quantity":46,"unitPrice":11},
    {"brand":"Childrens Night Time","sellerRef":"Jaxnation","quantity":85,"unitPrice":22},
    {"brand":"Mixture of Standardized and Non-Standardized Coastal Grasses","sellerRef":"Feedfire","quantity":68,"unitPrice":50},
    {"brand":"Chlorpromazine Hydrochloride","sellerRef":"Kamba","quantity":32,"unitPrice":26},
    {"brand":"Gleostine","sellerRef":"Twimm","quantity":18,"unitPrice":86},
    {"brand":"CVS Medicated Pads","sellerRef":"Yodoo","quantity":19,"unitPrice":41},
    {"brand":"Retin-A","sellerRef":"Twimbo","quantity":21,"unitPrice":33},
    {"brand":"Amazonian Colored Clay Foundation Broad Spectrum SPF 15 Sunscreen","sellerRef":"Livetube","quantity":88,"unitPrice":40},
    {"brand":"Hydrocodone Bitartrate and Acetaminophen","sellerRef":"Devpoint","quantity":24,"unitPrice":9},
    {"brand":"Metronidazole","sellerRef":"Voonix","quantity":21,"unitPrice":60},
    {"brand":"Alprazolam","sellerRef":"Tagopia","quantity":87,"unitPrice":61},
    {"brand":"Kepivance","sellerRef":"Pixope","quantity":90,"unitPrice":32},
    {"brand":"Chemtox","sellerRef":"JumpXS","quantity":81,"unitPrice":58},
    {"brand":"BACLOFEN","sellerRef":"Ainyx","quantity":17,"unitPrice":66},
    {"brand":"Gabapentin","sellerRef":"DabZ","quantity":71,"unitPrice":19},
    {"brand":"Topiramate","sellerRef":"Linkbuzz","quantity":23,"unitPrice":8},
    {"brand":"Warfarin Sodium","sellerRef":"Shuffletag","quantity":81,"unitPrice":85},
    {"brand":"Minus-Sol Facial Sun Protection Sunscreen Broad Spectrum SPF 30 Plus Ivory","sellerRef":"Voonte","quantity":78,"unitPrice":83},
    {"brand":"Advanced Hand Sanitizer","sellerRef":"Feednation","quantity":11,"unitPrice":90},
    {"brand":"donepezil hydrochloride","sellerRef":"Gabtune","quantity":53,"unitPrice":78},
    {"brand":"Tamoxifen Citrate","sellerRef":"Quinu","quantity":29,"unitPrice":4},
    {"brand":"Rhizopus oryzae","sellerRef":"Oyoloo","quantity":52,"unitPrice":33},
    {"brand":"Hazelnut","sellerRef":"Realbuzz","quantity":96,"unitPrice":46},
    {"brand":"Dove Men plus Care","sellerRef":"Demimbu","quantity":100,"unitPrice":16},
    {"brand":"Sulfamethoxazole and Trimethoprim","sellerRef":"Rhynoodle","quantity":6,"unitPrice":86},
    {"brand":"Sodium Chloride","sellerRef":"Dazzlesphere","quantity":23,"unitPrice":10},
    {"brand":"Isopropyl Alcohol","sellerRef":"Buzzster","quantity":32,"unitPrice":98},
    {"brand":"CVS Pharmacy Oil Free Faces SPF 30","sellerRef":"Flashset","quantity":78,"unitPrice":98},
    {"brand":"Bupropion Hydrochloride","sellerRef":"Oyoloo","quantity":28,"unitPrice":26},
    {"brand":"Antiseptic","sellerRef":"Mudo","quantity":33,"unitPrice":83},
    {"brand":"UV Capture Sun BB","sellerRef":"Photofeed","quantity":3,"unitPrice":73},
    {"brand":"Cetirizine Hydrochloride","sellerRef":"Rhyloo","quantity":19,"unitPrice":76},
    {"brand":"CLE DE PEAU BEAUTE CR COMPACT FOUNDATION","sellerRef":"Wordpedia","quantity":43,"unitPrice":85},
    {"brand":"TAZICEF","sellerRef":"Skivee","quantity":2,"unitPrice":86},
    {"brand":"Kadian","sellerRef":"Leexo","quantity":75,"unitPrice":80},
    {"brand":"Doxycycline Hyclate","sellerRef":"Ainyx","quantity":30,"unitPrice":92},
    {"brand":"4 in 1 Pressed Mineral SPF 15 Golden Medium","sellerRef":"Yozio","quantity":88,"unitPrice":33},
    {"brand":"Aruba Aloe Very Water Resistant Sunscreen","sellerRef":"Feedfire","quantity":51,"unitPrice":4},
    {"brand":"Esgic","sellerRef":"Oyoloo","quantity":65,"unitPrice":37},
    {"brand":"Aurum Prunus","sellerRef":"Ailane","quantity":38,"unitPrice":77},
    {"brand":"IMITREX","sellerRef":"Gabtune","quantity":74,"unitPrice":93},
    {"brand":"Advanced Eye Relief/ Redness Maximum Relief","sellerRef":"Tagtune","quantity":1,"unitPrice":26},
    {"brand":"Mary Kay Tinted Moisturizer Sunscreen SPF 20 Bronze 2 (Drug Facts)","sellerRef":"Livetube","quantity":78,"unitPrice":46},
    {"brand":"Skin Irritation","sellerRef":"Realpoint","quantity":85,"unitPrice":38},
    {"brand":"Cefdinir","sellerRef":"Skinix","quantity":11,"unitPrice":47},
    {"brand":"Glipizide","sellerRef":"Jaxworks","quantity":9,"unitPrice":69},
    {"brand":"Stool Softener","sellerRef":"Oyoyo","quantity":15,"unitPrice":100},
    {"brand":"Bengay Zero Degrees Menthol Pain Relieving","sellerRef":"Skyndu","quantity":35,"unitPrice":6},
    {"brand":"SEPIA OFFICINALIS","sellerRef":"Mycat","quantity":89,"unitPrice":5},
    {"brand":"North Burn Relief","sellerRef":"Topicshots","quantity":49,"unitPrice":8},
    {"brand":"Phytonadione","sellerRef":"Youtags","quantity":79,"unitPrice":86},
    {"brand":"Grama Grass","sellerRef":"Midel","quantity":86,"unitPrice":33},
    {"brand":"Levetiracetam","sellerRef":"Youspan","quantity":9,"unitPrice":75},
    {"brand":"SolMate","sellerRef":"Divavu","quantity":85,"unitPrice":27},
    {"brand":"ETHYL ALCOHOL","sellerRef":"Avaveo","quantity":29,"unitPrice":85},
    {"brand":"Attention Plus","sellerRef":"Jayo","quantity":49,"unitPrice":18},
    {"brand":"HAWAIIAN TROPIC","sellerRef":"Topicware","quantity":2,"unitPrice":48},
    {"brand":"CVS Medicated Heat 1 ct","sellerRef":"Kazu","quantity":6,"unitPrice":27},
    {"brand":"Allspice","sellerRef":"Pixope","quantity":67,"unitPrice":60},
    {"brand":"Chafe Rescue","sellerRef":"Snaptags","quantity":13,"unitPrice":37},
    {"brand":"bareMinerals READY Touch Up Veil Broad Spectrum SPF 15","sellerRef":"Brainlounge","quantity":15,"unitPrice":91},
    {"brand":"Prevantics Maxi Swabstick","sellerRef":"Topicware","quantity":29,"unitPrice":31},
    {"brand":"Head and Shoulders","sellerRef":"Yakitri","quantity":64,"unitPrice":57},
    {"brand":"ANTIBACTERIAL WIPES Lemon Drop","sellerRef":"Zoonder","quantity":55,"unitPrice":65},
    {"brand":"Nifedipine","sellerRef":"LiveZ","quantity":67,"unitPrice":18},
    {"brand":"Roxicodone","sellerRef":"Jabbersphere","quantity":46,"unitPrice":52},
    {"brand":"Fosamax","sellerRef":"Blogpad","quantity":17,"unitPrice":36},
    {"brand":"Valacyclovir hydrochloride","sellerRef":"Thoughtbridge","quantity":87,"unitPrice":40},
    {"brand":"Methocarbamol","sellerRef":"Quimba","quantity":96,"unitPrice":86},
    {"brand":"TOPIRAMATE","sellerRef":"Realpoint","quantity":26,"unitPrice":60},
    {"brand":"Rocky Mtn. Juniper Pollen","sellerRef":"Kaymbo","quantity":43,"unitPrice":93},
    {"brand":"Oxygen","sellerRef":"Twitterbeat","quantity":11,"unitPrice":74},
    {"brand":"fosphenytoin sodium","sellerRef":"Bluejam","quantity":12,"unitPrice":67},
    {"brand":"Epstein Barr Virus Remedy","sellerRef":"Gabvine","quantity":17,"unitPrice":63},
    {"brand":"Gold Bond Foot","sellerRef":"Yodel","quantity":90,"unitPrice":59},
    {"brand":"DR. RECKEWEG R63 Endangitin","sellerRef":"Mymm","quantity":85,"unitPrice":76},
    {"brand":"Antibacterial Moist Wipes","sellerRef":"Dablist","quantity":61,"unitPrice":15},
    {"brand":"Hydrochlorothiazide","sellerRef":"Aibox","quantity":55,"unitPrice":49},
    {"brand":"Red Ginseng Pure Red Lively Water","sellerRef":"Zazio","quantity":33,"unitPrice":82},
    {"brand":"Isopropyl Alcohol","sellerRef":"Aibox","quantity":98,"unitPrice":93},
    {"brand":"Levalbuterol","sellerRef":"Tagopia","quantity":96,"unitPrice":60},
    {"brand":"Crest Anti-Cavity","sellerRef":"Kwinu","quantity":75,"unitPrice":92},
    {"brand":"Vitafol","sellerRef":"Jamia","quantity":50,"unitPrice":11},
    {"brand":"Nicotine","sellerRef":"Eazzy","quantity":20,"unitPrice":45},
    {"brand":"Home Sense Ultra Green Apple Scent","sellerRef":"Devpulse","quantity":59,"unitPrice":18},
    {"brand":"Levetiracetam","sellerRef":"Wordware","quantity":17,"unitPrice":93},
    {"brand":"Zicam Naturals Cough Suppressant","sellerRef":"Linktype","quantity":16,"unitPrice":12},
    {"brand":"Albuterol Sulfate","sellerRef":"Trilith","quantity":74,"unitPrice":88},
    {"brand":"Black Birch","sellerRef":"Browsecat","quantity":100,"unitPrice":88},
    {"brand":"stila CC color correcting broad-spectrum SPF 20 02 LIGHT","sellerRef":"Browsedrive","quantity":97,"unitPrice":26},
    {"brand":"DIPYRIDAMOLE","sellerRef":"Quinu","quantity":8,"unitPrice":59},
    {"brand":"Gemfibrozil","sellerRef":"Realmix","quantity":14,"unitPrice":18},
    {"brand":"CD DiorSkin Radiant Base Skin-Refining Pro Lighting - 001","sellerRef":"Thoughtsphere","quantity":92,"unitPrice":57},
    {"brand":"Marlido Kit","sellerRef":"Kwilith","quantity":49,"unitPrice":40},
    {"brand":"LANOXIN","sellerRef":"Flashspan","quantity":20,"unitPrice":90},
    {"brand":"Doxazosin","sellerRef":"Devify","quantity":89,"unitPrice":76},
    {"brand":"Acyclovir","sellerRef":"Yata","quantity":59,"unitPrice":57},
    {"brand":"ERY-TAB","sellerRef":"Wordify","quantity":20,"unitPrice":67},
    {"brand":"Topcare Ibuprofen","sellerRef":"Topicware","quantity":68,"unitPrice":5},
    {"brand":"Aspergillus niger","sellerRef":"Rhynyx","quantity":20,"unitPrice":89},
    {"brand":"Niacor","sellerRef":"Oyoloo","quantity":5,"unitPrice":46},
    {"brand":"ONDANSETRON","sellerRef":"Skibox","quantity":58,"unitPrice":32},
    {"brand":"Glipizide","sellerRef":"Skynoodle","quantity":49,"unitPrice":71},
    {"brand":"Anagrelide Hydrochloride","sellerRef":"Yadel","quantity":77,"unitPrice":26},
    {"brand":"Hangover Help","sellerRef":"Katz","quantity":85,"unitPrice":89},
    {"brand":"Acetaminophen and Codeine Phosphate","sellerRef":"Tavu","quantity":9,"unitPrice":87},
    {"brand":"Night Time Cherry","sellerRef":"Twitterbridge","quantity":86,"unitPrice":63},
    {"brand":"CENTER-AL - AMARANTHUS RETROFLEXUS POLLEN","sellerRef":"Thoughtstorm","quantity":8,"unitPrice":46},
    {"brand":"Neurontin","sellerRef":"Zoonder","quantity":95,"unitPrice":6},
    {"brand":"Optiray","sellerRef":"Wikivu","quantity":4,"unitPrice":24},
    {"brand":"Glimepiride","sellerRef":"Topdrive","quantity":81,"unitPrice":73},
    {"brand":"Vasopressin","sellerRef":"Oyondu","quantity":41,"unitPrice":31},
    {"brand":"Cyclophosphamide","sellerRef":"Jabberbean","quantity":4,"unitPrice":6},
    {"brand":"Childrens Allergy","sellerRef":"Zoombox","quantity":78,"unitPrice":67},
    {"brand":"Bryonia Alba","sellerRef":"Quamba","quantity":72,"unitPrice":65},
    {"brand":"Formica Oxalis","sellerRef":"Fanoodle","quantity":71,"unitPrice":1},
    {"brand":"cold","sellerRef":"Yambee","quantity":28,"unitPrice":4},
    {"brand":"Exelon","sellerRef":"Bubbletube","quantity":75,"unitPrice":5},
    {"brand":"Olanzapine and Fluoxetine","sellerRef":"Linklinks","quantity":36,"unitPrice":69},
    {"brand":"Diclofenac Sodium","sellerRef":"Eazzy","quantity":45,"unitPrice":45},
    {"brand":"Psoriasis Skin Cream","sellerRef":"Browsetype","quantity":17,"unitPrice":62},
    {"brand":"Azithromycin","sellerRef":"Zoonder","quantity":6,"unitPrice":23},
    {"brand":"bareMinerals bareSkin Pure Brightening Serum Foundation Broad Spectrum SPF 20","sellerRef":"Flipbug","quantity":83,"unitPrice":68},
    {"brand":"Neutrogena Oil-Free Acne Wash","sellerRef":"Yamia","quantity":11,"unitPrice":87},
    {"brand":"kirkland signature minoxidil","sellerRef":"Aimbu","quantity":56,"unitPrice":56},
    {"brand":"Topcare Daily Facial","sellerRef":"Topicware","quantity":99,"unitPrice":1},
    {"brand":"Soft Care Foaming Antibacterial Hand","sellerRef":"Wikivu","quantity":28,"unitPrice":59},
    {"brand":"Nortriptyline Hydrochloride","sellerRef":"Babbleblab","quantity":71,"unitPrice":98},
    {"brand":"Metformin Hydrochloride","sellerRef":"Quamba","quantity":47,"unitPrice":77},
    {"brand":"Robinia Nicotiana","sellerRef":"Blogtags","quantity":97,"unitPrice":23},
    {"brand":"Famciclovir","sellerRef":"Oyoloo","quantity":74,"unitPrice":95},
    {"brand":"ZALEPLON","sellerRef":"Ainyx","quantity":91,"unitPrice":77},
    {"brand":"Heart Small Intestine Meridian Opener","sellerRef":"DabZ","quantity":100,"unitPrice":95},
    {"brand":"Acetadryl","sellerRef":"Dabshots","quantity":58,"unitPrice":75},
    {"brand":"Nitrotan","sellerRef":"Brightbean","quantity":62,"unitPrice":91},
    {"brand":"Pioglitazone Hydrochloride","sellerRef":"Eimbee","quantity":96,"unitPrice":2},
    {"brand":"Propranolol Hydrochloride","sellerRef":"Twitterbridge","quantity":17,"unitPrice":77},
    {"brand":"Thiothixene","sellerRef":"Skivee","quantity":48,"unitPrice":5},
    {"brand":"Amlodipine besylate","sellerRef":"Cogilith","quantity":3,"unitPrice":42},
    {"brand":"Isordil","sellerRef":"Thoughtworks","quantity":95,"unitPrice":54},
    {"brand":"Childrens Cetirizine Hydrochloride","sellerRef":"Skilith","quantity":66,"unitPrice":6},
    {"brand":"Simvastatin","sellerRef":"Skyndu","quantity":86,"unitPrice":45},
    {"brand":"Neuro Support Plus Foot Balm","sellerRef":"Realfire","quantity":41,"unitPrice":39},
    {"brand":"Good Sense Mucus Relief","sellerRef":"Skyble","quantity":33,"unitPrice":85},
    {"brand":"lice","sellerRef":"Meejo","quantity":75,"unitPrice":46},
    {"brand":"Alcohol Free","sellerRef":"Quinu","quantity":19,"unitPrice":29},
    {"brand":"Insomnia","sellerRef":"Twinder","quantity":72,"unitPrice":82},
    {"brand":"Epicoccum","sellerRef":"Lajo","quantity":79,"unitPrice":91},
    {"brand":"Good Neighbor Pharmacy Cough DM ER","sellerRef":"Jaxspan","quantity":65,"unitPrice":59},
    {"brand":"nighttime sleep aid","sellerRef":"Jabbertype","quantity":26,"unitPrice":13},
    {"brand":"HYPERICUM PERFORATUM","sellerRef":"Kamba","quantity":2,"unitPrice":6},
    {"brand":"Chlorpromazine Hydrochloride","sellerRef":"Tagchat","quantity":14,"unitPrice":48},
    {"brand":"Dronabinol","sellerRef":"Abatz","quantity":3,"unitPrice":87},
    {"brand":"Glyburide","sellerRef":"Devify","quantity":55,"unitPrice":89},
    {"brand":"Tomato","sellerRef":"Digitube","quantity":13,"unitPrice":62},
    {"brand":"Hand Kleen Southern OrchardAntibacterial Han","sellerRef":"Skivee","quantity":43,"unitPrice":81},
    {"brand":"Pramipexole Dihydrochloride","sellerRef":"Rhynoodle","quantity":57,"unitPrice":12},
    {"brand":"Ranitidine","sellerRef":"Mydeo","quantity":51,"unitPrice":11},
    {"brand":"Methocarbamol","sellerRef":"Jabberbean","quantity":10,"unitPrice":19},
    {"brand":"ANTIBACTERIAL HAND SP WITH LIGHT MOISTURIZERS","sellerRef":"Minyx","quantity":97,"unitPrice":36},
    {"brand":"Vichy Laboratoires Normaderm Pro Mat","sellerRef":"Voonte","quantity":36,"unitPrice":67},
    {"brand":"Neutrogena Ultra Sheer Dry Touch Sunblock","sellerRef":"Yakidoo","quantity":6,"unitPrice":88},
    {"brand":"NUCYNTA","sellerRef":"Flashspan","quantity":87,"unitPrice":80},
    {"brand":"Smart Sense all day allergy","sellerRef":"Agimba","quantity":78,"unitPrice":62},
    {"brand":"Zicam","sellerRef":"Voolith","quantity":57,"unitPrice":39},
    {"brand":"Hydromorphone HCl","sellerRef":"Dazzlesphere","quantity":41,"unitPrice":42},
    {"brand":"MEDICAL AIR","sellerRef":"Bubblebox","quantity":97,"unitPrice":18},
    {"brand":"PENICILLIN G POTASSIUM","sellerRef":"Shufflebeat","quantity":95,"unitPrice":22},
    {"brand":"Aleveer Patch","sellerRef":"Twitterbeat","quantity":78,"unitPrice":51},
    {"brand":"Dg Health pain reliever","sellerRef":"Twimm","quantity":62,"unitPrice":69},
    {"brand":"Live Better","sellerRef":"Trilith","quantity":55,"unitPrice":61},
    {"brand":"Medi-First Plus Sterile Alcohol Pads","sellerRef":"Twimm","quantity":26,"unitPrice":90},
    {"brand":"SANAFITIL","sellerRef":"Aibox","quantity":3,"unitPrice":14},
    {"brand":"Cutivate","sellerRef":"Jabbercube","quantity":74,"unitPrice":75},
    {"brand":"Antiseptic","sellerRef":"Mudo","quantity":69,"unitPrice":5},
    {"brand":"Ketoconazole","sellerRef":"Myworks","quantity":93,"unitPrice":6},
    {"brand":"Justice Fruit Scent ANTI BAC HAND SANITIZER","sellerRef":"Flashdog","quantity":65,"unitPrice":2},
    {"brand":"Clear Proof Acne System The Go Set","sellerRef":"Dabtype","quantity":88,"unitPrice":5},
    {"brand":"DIPYRIDAMOLE","sellerRef":"Realcube","quantity":52,"unitPrice":83},
    {"brand":"Alendronate Sodium","sellerRef":"Tambee","quantity":47,"unitPrice":64},
    {"brand":"Premier Value day time severe cold and cough","sellerRef":"Plambee","quantity":6,"unitPrice":25},
    {"brand":"Tiny Tillia","sellerRef":"Shuffletag","quantity":79,"unitPrice":77},
    {"brand":"Vicoprofen","sellerRef":"Divape","quantity":22,"unitPrice":20},
    {"brand":"e-HCG","sellerRef":"Jaxnation","quantity":10,"unitPrice":99},
    {"brand":"Magnesium Citrate","sellerRef":"Skippad","quantity":19,"unitPrice":73},
    {"brand":"Risperidone","sellerRef":"Thoughtmix","quantity":47,"unitPrice":16},
    {"brand":"Sancuso","sellerRef":"Npath","quantity":12,"unitPrice":5},
    {"brand":"Flector","sellerRef":"Skalith","quantity":87,"unitPrice":34},
    {"brand":"Sweet Gum","sellerRef":"Gabvine","quantity":22,"unitPrice":28},
    {"brand":"Losartan Potassium and Hydrochlorothiazide","sellerRef":"Brainbox","quantity":18,"unitPrice":98},
    {"brand":"mark. get a tint","sellerRef":"Twinder","quantity":72,"unitPrice":1},
    {"brand":"Escitalopram","sellerRef":"Yata","quantity":73,"unitPrice":50},
    {"brand":"G-Tuss-NL","sellerRef":"Pixope","quantity":96,"unitPrice":30},
    {"brand":"Loratadine","sellerRef":"Fivespan","quantity":78,"unitPrice":37},
    {"brand":"CHENOPODIUM ALBUM POLLEN","sellerRef":"Kwideo","quantity":58,"unitPrice":99},
    {"brand":"Propranolol Hydrochloride","sellerRef":"Trilith","quantity":5,"unitPrice":23},
    {"brand":"Nilandron","sellerRef":"Mita","quantity":97,"unitPrice":75},
    {"brand":"Disney PLANES FIRE and RESCUE ANTIBACTERIAL HAND WIPES","sellerRef":"Katz","quantity":6,"unitPrice":68},
    {"brand":"Treatment Set TS351004","sellerRef":"Realbridge","quantity":21,"unitPrice":61},
    {"brand":"Rizatriptan Benzoate","sellerRef":"Dynabox","quantity":70,"unitPrice":53},
    {"brand":"Green Guard Pain and Ache Relief","sellerRef":"Youspan","quantity":98,"unitPrice":25},
    {"brand":"Passion Fruit Kiss","sellerRef":"Quatz","quantity":85,"unitPrice":11},
    {"brand":"Olanzapine","sellerRef":"Eamia","quantity":52,"unitPrice":84},
    {"brand":"GMC Medical","sellerRef":"Minyx","quantity":46,"unitPrice":14},
    {"brand":"Metformin Hydrochloride","sellerRef":"Dazzlesphere","quantity":57,"unitPrice":88},
    {"brand":"Imipenem and Cilastatin","sellerRef":"Voonder","quantity":37,"unitPrice":22},
    {"brand":"LBEL COULEUR LUXE AMPLIFIER XP","sellerRef":"Quimba","quantity":30,"unitPrice":14},
    {"brand":"Peach Mango Anti-Bacterial Hand Sanitizer","sellerRef":"Bluezoom","quantity":20,"unitPrice":69},
    {"brand":"Carp","sellerRef":"Jaloo","quantity":48,"unitPrice":60},
    {"brand":"Risperidone","sellerRef":"Janyx","quantity":50,"unitPrice":57},
    {"brand":"Haloperidol Decanoate","sellerRef":"Flashdog","quantity":87,"unitPrice":7},
    {"brand":"Non Drowsy Cold and Cough PE","sellerRef":"Zoombeat","quantity":85,"unitPrice":38},
    {"brand":"Risperidone","sellerRef":"Einti","quantity":34,"unitPrice":85},
    {"brand":"Oxazepam","sellerRef":"Topicware","quantity":96,"unitPrice":25},
    {"brand":"Rx Act Tussin CF","sellerRef":"Roomm","quantity":40,"unitPrice":73},
    {"brand":"SPF30 SUPER SENSITIVE SUNSCREEN","sellerRef":"Photospace","quantity":17,"unitPrice":89},
    {"brand":"Vinorelbine","sellerRef":"Skipfire","quantity":69,"unitPrice":57},
    {"brand":"Berberis Populus","sellerRef":"Topicshots","quantity":37,"unitPrice":83},
    {"brand":"ERY-TAB","sellerRef":"Voolia","quantity":82,"unitPrice":16},
    {"brand":"BONTRIL","sellerRef":"Katz","quantity":36,"unitPrice":6},
    {"brand":"Atopalm First Aid Triple Antibiotic","sellerRef":"Quaxo","quantity":29,"unitPrice":48},
    {"brand":"Teething","sellerRef":"Oyoba","quantity":31,"unitPrice":45},
    {"brand":"BANANA BOAT","sellerRef":"Kwimbee","quantity":23,"unitPrice":90},
    {"brand":"Non Aspirin PM","sellerRef":"Babbleblab","quantity":67,"unitPrice":56},
    {"brand":"Amidate","sellerRef":"Demivee","quantity":63,"unitPrice":78},
    {"brand":"equate acetaminophen","sellerRef":"Aimbu","quantity":84,"unitPrice":14},
    {"brand":"IBUPROFEN","sellerRef":"Trudeo","quantity":99,"unitPrice":43},
    {"brand":"NATRUM SULPHURICUM","sellerRef":"Chatterbridge","quantity":100,"unitPrice":23},
    {"brand":"Concerta","sellerRef":"Tagfeed","quantity":2,"unitPrice":21},
    {"brand":"BENAZEPRIL HYDROCHLORIDE","sellerRef":"Topdrive","quantity":54,"unitPrice":10},
    {"brand":"REXALL HEMORRHOIDAL COOLING","sellerRef":"Brainbox","quantity":82,"unitPrice":78},
    {"brand":"Warts","sellerRef":"Yata","quantity":42,"unitPrice":17},
    {"brand":"Glytone Suncare SPF 50","sellerRef":"Pixoboo","quantity":43,"unitPrice":81},
    {"brand":"Ranitidine","sellerRef":"Jatri","quantity":84,"unitPrice":95},
    {"brand":"Tribenzor","sellerRef":"Abata","quantity":35,"unitPrice":51},
    {"brand":"Wormwood","sellerRef":"Linkbridge","quantity":17,"unitPrice":89},
    {"brand":"diphenhydramine hydrochloride","sellerRef":"Twinte","quantity":36,"unitPrice":76},
    {"brand":"Equate Day time","sellerRef":"Photobug","quantity":9,"unitPrice":58},
    {"brand":"PVP Iodine Prep Swabstick","sellerRef":"Rhycero","quantity":90,"unitPrice":51},
    {"brand":"Lisinopril with Hydrochlorothiazide","sellerRef":"Yoveo","quantity":51,"unitPrice":55},
    {"brand":"BUPROPION HYDROCHLORIDE","sellerRef":"Voonix","quantity":14,"unitPrice":87},
    {"brand":"Amlodipine Besylate","sellerRef":"Topiczoom","quantity":41,"unitPrice":37},
    {"brand":"Neutrogena SkinClearing","sellerRef":"Dablist","quantity":7,"unitPrice":59},
    {"brand":"Flounder","sellerRef":"Brainbox","quantity":10,"unitPrice":86},
    {"brand":"Sertraline Hydrochloride","sellerRef":"Yodoo","quantity":94,"unitPrice":43},
    {"brand":"Citalopram Hydrobromide","sellerRef":"Brainverse","quantity":96,"unitPrice":95},
    {"brand":"topcare cold and flu night time","sellerRef":"Trilia","quantity":5,"unitPrice":76},
    {"brand":"Blue Cross Laboratories","sellerRef":"Edgepulse","quantity":48,"unitPrice":52},
    {"brand":"good neighbor pharmacy pain relief","sellerRef":"Teklist","quantity":44,"unitPrice":65},
    {"brand":"Olanzapine","sellerRef":"Zooveo","quantity":14,"unitPrice":96},
    {"brand":"ATORVASTATIN CALCIUM","sellerRef":"Reallinks","quantity":84,"unitPrice":21},
    {"brand":"Fludarabine Phosphate","sellerRef":"Edgewire","quantity":83,"unitPrice":94},
    {"brand":"Lidocaine Hydrochloride and Epinephrine","sellerRef":"Wikivu","quantity":99,"unitPrice":76},
    {"brand":"AVAGE","sellerRef":"Thoughtsphere","quantity":64,"unitPrice":76},
    {"brand":"Nite Time","sellerRef":"Fivebridge","quantity":84,"unitPrice":70},
    {"brand":"Nabumetone","sellerRef":"Thoughtstorm","quantity":89,"unitPrice":26},
    {"brand":"Melphalan Hydrochloride","sellerRef":"Skipfire","quantity":32,"unitPrice":63},
    {"brand":"Your Label Here Hydrogen Peroxide First Aid","sellerRef":"Skinix","quantity":34,"unitPrice":74},
    {"brand":"REHYDRATE","sellerRef":"DabZ","quantity":71,"unitPrice":71},
    {"brand":"Headache Relief","sellerRef":"Photofeed","quantity":9,"unitPrice":87},
    {"brand":"Oxygen","sellerRef":"Cogilith","quantity":63,"unitPrice":42},
    {"brand":"Chrysolith Retina","sellerRef":"Avavee","quantity":44,"unitPrice":25},
    {"brand":"EASTERN COTTONWOOD POLLEN","sellerRef":"Camimbo","quantity":84,"unitPrice":99},
    {"brand":"acid reducer","sellerRef":"Nlounge","quantity":100,"unitPrice":99},
    {"brand":"Time Machine BB","sellerRef":"Fadeo","quantity":38,"unitPrice":68},
    {"brand":"Moisturizing Hand Sanitizer","sellerRef":"Izio","quantity":16,"unitPrice":93},
    {"brand":"Nortriptyline Hydrochloride","sellerRef":"Jaxspan","quantity":51,"unitPrice":48},
    {"brand":"Isopto Tears","sellerRef":"Twitterlist","quantity":26,"unitPrice":80},
    {"brand":"Venlafaxine","sellerRef":"Babbleset","quantity":54,"unitPrice":10},
    {"brand":"Potassium Citrate","sellerRef":"Kwilith","quantity":68,"unitPrice":97},
    {"brand":"Promethazine Hydrochloride","sellerRef":"Trunyx","quantity":35,"unitPrice":28},
    {"brand":"Medroxyprogesterone Acetate","sellerRef":"Livefish","quantity":77,"unitPrice":90},
    {"brand":"Sunmark z-sleep","sellerRef":"Shuffletag","quantity":22,"unitPrice":23},
    {"brand":"Nutricel Additive Solution - CP2D","sellerRef":"Jaloo","quantity":85,"unitPrice":97},
    {"brand":"Gas Relief","sellerRef":"Dabjam","quantity":16,"unitPrice":92},
    {"brand":"Diclofenac Sodium and Misoprostol","sellerRef":"Centidel","quantity":86,"unitPrice":18},
    {"brand":"Hydroxyzine Hydrochloride","sellerRef":"Twitternation","quantity":95,"unitPrice":95},
    {"brand":"Mometasone Furoate","sellerRef":"Flipstorm","quantity":31,"unitPrice":10},
    {"brand":"Risperidone","sellerRef":"Quatz","quantity":81,"unitPrice":4},
    {"brand":"METFORMIN HYDROCHLORIDE","sellerRef":"Meedoo","quantity":85,"unitPrice":22},
    {"brand":"Tarka","sellerRef":"Photobug","quantity":88,"unitPrice":13},
    {"brand":"Candesartan cilexetil","sellerRef":"Riffpath","quantity":27,"unitPrice":64},
    {"brand":"JUNIPERUS VIRGINIANA POLLEN","sellerRef":"Tazzy","quantity":66,"unitPrice":18},
    {"brand":"OHUI THE FIRST CELL REVOLUTION AGE CONTROL SUN BLOCK","sellerRef":"Youspan","quantity":74,"unitPrice":28},
    {"brand":"Assured","sellerRef":"Zava","quantity":91,"unitPrice":59},
    {"brand":"Aveeno Baby Natural Protection Face","sellerRef":"Vipe","quantity":81,"unitPrice":22},
    {"brand":"Colgate Optic White","sellerRef":"Twitterbridge","quantity":76,"unitPrice":38},
    {"brand":"VALPROIC ACID","sellerRef":"Yombu","quantity":26,"unitPrice":1},
    {"brand":"SHISEIDO ADVANCED HYDRO-LIQUID COMPACT (REFILL)","sellerRef":"Leexo","quantity":40,"unitPrice":84},
    {"brand":"Desipramine Hydrochloride","sellerRef":"Edgeblab","quantity":61,"unitPrice":34},
    {"brand":"Hydrochlorothiazide","sellerRef":"Tavu","quantity":11,"unitPrice":95},
    {"brand":"WHITE FLOWER ANALGESIC BALM","sellerRef":"Pixonyx","quantity":78,"unitPrice":14},
    {"brand":"Nitrofurantion Macrocrystals","sellerRef":"Aimbo","quantity":69,"unitPrice":88},
    {"brand":"AllergyCare","sellerRef":"Fivechat","quantity":48,"unitPrice":12},
    {"brand":"Glimepiride","sellerRef":"Jetpulse","quantity":73,"unitPrice":84},
    {"brand":"Ascorbic Acid","sellerRef":"Jayo","quantity":47,"unitPrice":34},
    {"brand":"Standardized Grass Pollen, Grass Mix 5","sellerRef":"Photobean","quantity":59,"unitPrice":1},
    {"brand":"Citalopram","sellerRef":"Thoughtworks","quantity":42,"unitPrice":17},
    {"brand":"Green Guard Pain and Ache Relief","sellerRef":"Kwinu","quantity":30,"unitPrice":90},
    {"brand":"LBEL","sellerRef":"Fivechat","quantity":34,"unitPrice":10},
    {"brand":"Clonazepam","sellerRef":"Eazzy","quantity":13,"unitPrice":63},
    {"brand":"Pep-Back","sellerRef":"Dynabox","quantity":44,"unitPrice":12},
    {"brand":"RoC Multi Correxion 4 Zone Daily Moisturizer","sellerRef":"Blogpad","quantity":81,"unitPrice":61},
    {"brand":"Angeliq","sellerRef":"Roodel","quantity":44,"unitPrice":88},
    {"brand":"ADENOSINE","sellerRef":"Oyoloo","quantity":73,"unitPrice":100},
    {"brand":"BETULA LENTA POLLEN","sellerRef":"Jaxspan","quantity":63,"unitPrice":83},
    {"brand":"Cefepime","sellerRef":"Eadel","quantity":84,"unitPrice":41},
    {"brand":"SunscreenSPF 30","sellerRef":"Livepath","quantity":83,"unitPrice":48},
    {"brand":"Gabapentin","sellerRef":"Wikivu","quantity":28,"unitPrice":35},
    {"brand":"Nortriptyline Hydrochloride","sellerRef":"Voolia","quantity":28,"unitPrice":89},
    {"brand":"Loratadine and Pseudoephedrine Sulfate","sellerRef":"Shufflester","quantity":74,"unitPrice":63},
    {"brand":"Morphine Sulfate","sellerRef":"Tanoodle","quantity":76,"unitPrice":90},
    {"brand":"Dipyridamole","sellerRef":"Meedoo","quantity":47,"unitPrice":12},
    {"brand":"Terazosin Hydrochloride","sellerRef":"Vinder","quantity":98,"unitPrice":23},
    {"brand":"Tamiflu","sellerRef":"Youtags","quantity":26,"unitPrice":54},
    {"brand":"Adenosine","sellerRef":"Agimba","quantity":17,"unitPrice":13},
    {"brand":"Xanax","sellerRef":"Vipe","quantity":88,"unitPrice":69},
    {"brand":"Povidone-Iodine Scrub Swabsticks","sellerRef":"Dabtype","quantity":29,"unitPrice":45},
    {"brand":"OVACE","sellerRef":"Tagfeed","quantity":12,"unitPrice":86},
    {"brand":"Pure Finish Mineral Tinted Moisturizer SPF 15 Light","sellerRef":"Skidoo","quantity":96,"unitPrice":48},
    {"brand":"Repara","sellerRef":"Aimbu","quantity":34,"unitPrice":50},
    {"brand":"Night Time Cherry","sellerRef":"Bluejam","quantity":10,"unitPrice":4},
    {"brand":"AlphaNine","sellerRef":"Photojam","quantity":73,"unitPrice":2},
    {"brand":"PENICILLIN G PROCAINE","sellerRef":"Vipe","quantity":86,"unitPrice":7},
    {"brand":"Tormentilla Cochlearia","sellerRef":"Tagchat","quantity":80,"unitPrice":46},
    {"brand":"PreNatal Vitamins Plus","sellerRef":"Oodoo","quantity":19,"unitPrice":41},
    {"brand":"SohMed Allergy","sellerRef":"Photobug","quantity":87,"unitPrice":94},
    {"brand":"CARBAMAZEPINE","sellerRef":"Zooveo","quantity":4,"unitPrice":67},
    {"brand":"LYCOPODIUM CLAVATUM","sellerRef":"Browsecat","quantity":36,"unitPrice":64},
    {"brand":"Risperidone","sellerRef":"Photobug","quantity":36,"unitPrice":70},
    {"brand":"LBEL HYDRATESS","sellerRef":"Youtags","quantity":86,"unitPrice":89},
    {"brand":"Rescon GG","sellerRef":"Twimbo","quantity":85,"unitPrice":35},
    {"brand":"ESZOPICLONE","sellerRef":"Eire","quantity":83,"unitPrice":60},
    {"brand":"3 Pack Instant Hand Sanitizer with moisturizers Aloe Scented","sellerRef":"Brainbox","quantity":12,"unitPrice":69},
    {"brand":"Hydrocortisone","sellerRef":"Kayveo","quantity":60,"unitPrice":93},
    {"brand":"Selsun Blue Moisturizing","sellerRef":"Centidel","quantity":43,"unitPrice":39},
    {"brand":"Herpetrol","sellerRef":"Riffpath","quantity":49,"unitPrice":92},
    {"brand":"Green Tussin","sellerRef":"Photobean","quantity":2,"unitPrice":18},
    {"brand":"Topical Hemo-Stat","sellerRef":"Tagchat","quantity":45,"unitPrice":51},
    {"brand":"Sulfur Colloid","sellerRef":"Muxo","quantity":98,"unitPrice":4},
    {"brand":"clear days ahead","sellerRef":"Meemm","quantity":24,"unitPrice":79},
    {"brand":"Anticavity Fluoride Rinse","sellerRef":"Muxo","quantity":98,"unitPrice":19},
    {"brand":"Pier 1 Imports Lily blossom Anti-Bacterial Hand Sanitizer","sellerRef":"Ntag","quantity":67,"unitPrice":7},
    {"brand":"Amoxicillin","sellerRef":"Jayo","quantity":27,"unitPrice":46},
    {"brand":"Isometheptene Mucate, Caffeine, and Acetaminophen","sellerRef":"Tagtune","quantity":18,"unitPrice":84},
    {"brand":"Captopril","sellerRef":"Zoovu","quantity":33,"unitPrice":99},
    {"brand":"Levetiracetam","sellerRef":"Digitube","quantity":70,"unitPrice":51},
    {"brand":"Diovan","sellerRef":"Tagopia","quantity":61,"unitPrice":11},
    {"brand":"Amlodipine Besylate","sellerRef":"Voonix","quantity":56,"unitPrice":64},
    {"brand":"All-Nite Cold and Flu","sellerRef":"Zooveo","quantity":95,"unitPrice":38},
    {"brand":"Crest Pro-Health","sellerRef":"Twinte","quantity":80,"unitPrice":37},
    {"brand":"Dorzolamide Hydrochloride Ophthalmic Solution 2%, 10mL","sellerRef":"Skaboo","quantity":12,"unitPrice":91},
    {"brand":"Felodipine","sellerRef":"Yodel","quantity":64,"unitPrice":80},
    {"brand":"Plak Smacker","sellerRef":"Tagopia","quantity":14,"unitPrice":51},
    {"brand":"Clinical Works Ocean Breeze Waterless Hand Sanitizer","sellerRef":"Voonder","quantity":14,"unitPrice":85},
    {"brand":"antiperspirant deodorant","sellerRef":"Dynabox","quantity":81,"unitPrice":20},
    {"brand":"West Cottonwood","sellerRef":"Topicshots","quantity":54,"unitPrice":78},
    {"brand":"Meijer","sellerRef":"Dynazzy","quantity":98,"unitPrice":69},
    {"brand":"Fentanyl","sellerRef":"Topiclounge","quantity":42,"unitPrice":67},
    {"brand":"Antacid Antigas","sellerRef":"Thoughtworks","quantity":42,"unitPrice":63},
    {"brand":"Hair Regrowth Treatment","sellerRef":"Snaptags","quantity":98,"unitPrice":8},
    {"brand":"NATRUM MURIATICUM","sellerRef":"Fadeo","quantity":46,"unitPrice":5},
    {"brand":"4-N-1 WASH","sellerRef":"Vidoo","quantity":22,"unitPrice":99},
    {"brand":"Cranberry Antibacterial Foaming Hand Wash","sellerRef":"Agivu","quantity":80,"unitPrice":33},
    {"brand":"Rapamune","sellerRef":"Shuffletag","quantity":25,"unitPrice":49},
    {"brand":"G-Xpect PSE","sellerRef":"Pixoboo","quantity":44,"unitPrice":40},
    {"brand":"SHISEIDO THE MAKEUP PERFECT SMOOTHING COMPACT FOUNDATION (Refill)","sellerRef":"Realcube","quantity":98,"unitPrice":59},
    {"brand":"BERMUDA GRASS SMUT","sellerRef":"Wikizz","quantity":14,"unitPrice":78},
    {"brand":"TOPIRAMATE","sellerRef":"Twinte","quantity":44,"unitPrice":57},
    {"brand":"Risperidone","sellerRef":"Eidel","quantity":80,"unitPrice":33},
    {"brand":"Hydroxyzine","sellerRef":"Skinix","quantity":51,"unitPrice":14},
    {"brand":"Magnacet","sellerRef":"Skyba","quantity":22,"unitPrice":91},
    {"brand":"ReCreate Foundation","sellerRef":"Jabberstorm","quantity":33,"unitPrice":14},
    {"brand":"Donatussin DM Drops","sellerRef":"Zazio","quantity":72,"unitPrice":99},
    {"brand":"Vaseline","sellerRef":"Browseblab","quantity":23,"unitPrice":94},
    {"brand":"Nafcillin Sodium","sellerRef":"Browsebug","quantity":17,"unitPrice":93},
    {"brand":"Trecator","sellerRef":"Topicshots","quantity":98,"unitPrice":23},
    {"brand":"Prednisone","sellerRef":"Dablist","quantity":87,"unitPrice":76},
    {"brand":"Nicotine Polacrilex, Original","sellerRef":"Dabtype","quantity":80,"unitPrice":69},
    {"brand":"Pain Relief PM","sellerRef":"Skidoo","quantity":38,"unitPrice":97},
    {"brand":"Myrbetriq","sellerRef":"Blogpad","quantity":65,"unitPrice":64},
    {"brand":"Gabapentin","sellerRef":"Fanoodle","quantity":38,"unitPrice":89},
    {"brand":"Duloxetine Hydrochloride","sellerRef":"Abatz","quantity":53,"unitPrice":46},
    {"brand":"Famotidine","sellerRef":"Meejo","quantity":28,"unitPrice":67},
    {"brand":"Flecainide Acetate","sellerRef":"Flipopia","quantity":17,"unitPrice":42},
    {"brand":"Almacone","sellerRef":"Topicshots","quantity":50,"unitPrice":23},
    {"brand":"Ciprofloxacin","sellerRef":"Yozio","quantity":29,"unitPrice":43},
    {"brand":"Constipation","sellerRef":"Livepath","quantity":99,"unitPrice":77},
    {"brand":"Bupropion Hydrochloride","sellerRef":"Aivee","quantity":62,"unitPrice":34},
    {"brand":"Sulfasalazine","sellerRef":"Latz","quantity":8,"unitPrice":44},
    {"brand":"METHADONE HYDROCHLORIDE","sellerRef":"Wikivu","quantity":85,"unitPrice":99},
    {"brand":"Ferrum silicicum Urtica","sellerRef":"Omba","quantity":93,"unitPrice":35},
    {"brand":"Chestrub","sellerRef":"Voomm","quantity":41,"unitPrice":55},
    {"brand":"Atorvastatin Calcium","sellerRef":"Buzzbean","quantity":75,"unitPrice":47},
    {"brand":"Ondansetron","sellerRef":"Quinu","quantity":2,"unitPrice":19},
    {"brand":"Cefdinir","sellerRef":"Dablist","quantity":11,"unitPrice":41},
    {"brand":"Pediacare Childrens Allergy","sellerRef":"Kimia","quantity":98,"unitPrice":97},
    {"brand":"Lisinopril","sellerRef":"Thoughtbeat","quantity":71,"unitPrice":20},
    {"brand":"Good Sense ibuprofen","sellerRef":"Oozz","quantity":87,"unitPrice":57},
    {"brand":"Metformin Hydrochloride","sellerRef":"Skinix","quantity":90,"unitPrice":62},
    {"brand":"Watercress","sellerRef":"Centimia","quantity":50,"unitPrice":96},
    {"brand":"ATORVASTATIN CALCIUM","sellerRef":"Mynte","quantity":38,"unitPrice":4},
    {"brand":"EpiPen Jr","sellerRef":"Twinder","quantity":17,"unitPrice":47},
    {"brand":"THE YEON LOTUS FLOWER BC CUSHION PACT","sellerRef":"Photofeed","quantity":57,"unitPrice":62},
    {"brand":"Plegridy","sellerRef":"Linklinks","quantity":95,"unitPrice":19},
    {"brand":"RENO CAPS","sellerRef":"Quatz","quantity":9,"unitPrice":61},
    {"brand":"Topiramate","sellerRef":"JumpXS","quantity":52,"unitPrice":27},
    {"brand":"Alendronate Sodium","sellerRef":"Jamia","quantity":57,"unitPrice":37},
    {"brand":"Tree of Heaven","sellerRef":"Riffpath","quantity":26,"unitPrice":7},
    {"brand":"Acetaminophen And Codeine","sellerRef":"Tagpad","quantity":10,"unitPrice":14},
    {"brand":"Preferred Plus 12 Hour Nasal","sellerRef":"Cogidoo","quantity":44,"unitPrice":20},
    {"brand":"Topcare Sinus Congestion and Pain","sellerRef":"Tavu","quantity":48,"unitPrice":92},
    {"brand":"equaline aller ease","sellerRef":"Dazzlesphere","quantity":69,"unitPrice":59},
    {"brand":"MALE POWERHOUSE","sellerRef":"Jabbercube","quantity":53,"unitPrice":91},
    {"brand":"Nasohist","sellerRef":"Shuffletag","quantity":31,"unitPrice":63},
    {"brand":"EUCALYPTUS GLOBULUS POLLEN","sellerRef":"Thoughtbeat","quantity":14,"unitPrice":6},
    {"brand":"Potassium Chloride in Lactated Ringers and Dextrose","sellerRef":"Snaptags","quantity":35,"unitPrice":31},
    {"brand":"Phoma glomerata","sellerRef":"Edgeblab","quantity":36,"unitPrice":5},
    {"brand":"Pyril D","sellerRef":"Kimia","quantity":5,"unitPrice":46},
    {"brand":"Drymarine","sellerRef":"Mybuzz","quantity":5,"unitPrice":74},
    {"brand":"Endometrin","sellerRef":"Shuffledrive","quantity":43,"unitPrice":49},
    {"brand":"Olanzapine","sellerRef":"Yata","quantity":10,"unitPrice":89},
    {"brand":"CD DiorSkin Forever Flawless Perfection Fusion Wear Makeup SPF 25 - 022","sellerRef":"Layo","quantity":25,"unitPrice":51},
    {"brand":"CURAD Hydrogen Peroxide","sellerRef":"Layo","quantity":97,"unitPrice":84},
    {"brand":"Candida-Ease","sellerRef":"Demizz","quantity":44,"unitPrice":47},
    {"brand":"ATORVASTATIN CALCIUM","sellerRef":"Thoughtstorm","quantity":53,"unitPrice":73},
    {"brand":"SPF 20 UVA/UVB","sellerRef":"Topdrive","quantity":72,"unitPrice":80},
    {"brand":"Trexall","sellerRef":"Demizz","quantity":21,"unitPrice":13},
    {"brand":"UV LOCK ULTRA MILK SUN","sellerRef":"Brightdog","quantity":94,"unitPrice":30},
    {"brand":"Trauma Relief Gel","sellerRef":"Oloo","quantity":89,"unitPrice":69},
    {"brand":"smart sense allergy relief","sellerRef":"Babblestorm","quantity":48,"unitPrice":31},
    {"brand":"Nexium 24HR","sellerRef":"Twitterbeat","quantity":31,"unitPrice":20},
    {"brand":"anti nausea","sellerRef":"Zoonder","quantity":88,"unitPrice":73},
    {"brand":"Diazepam","sellerRef":"Skyndu","quantity":75,"unitPrice":30},
    {"brand":"Azolen","sellerRef":"Feedmix","quantity":92,"unitPrice":28},
    {"brand":"Analgesic Creme Rub","sellerRef":"Tagopia","quantity":98,"unitPrice":58},
    {"brand":"Antibacterial Hand -Vanilla Brown Sugar","sellerRef":"Gigashots","quantity":88,"unitPrice":33},
    {"brand":"REYATAZ","sellerRef":"Tazz","quantity":67,"unitPrice":61},
    {"brand":"Face and Body Sunscreen SPF 35","sellerRef":"Realblab","quantity":2,"unitPrice":80},
    {"brand":"AHAVA ACTIVE DEADSEA MINERALS","sellerRef":"Leenti","quantity":68,"unitPrice":4},
    {"brand":"OXYGEN, REFRIGERATED LIQUID","sellerRef":"Thoughtblab","quantity":46,"unitPrice":90},
    {"brand":"Treatment Set TS331258","sellerRef":"Buzzster","quantity":41,"unitPrice":100},
    {"brand":"AMITRIPTYLINE HYDROCHLORIDE","sellerRef":"Quaxo","quantity":72,"unitPrice":36},
    {"brand":"Moisturizing Face Screen SPF 30","sellerRef":"Meedoo","quantity":13,"unitPrice":86},
    {"brand":"Creamy Peach Antibacterial Foaming Hand Wash","sellerRef":"Avaveo","quantity":5,"unitPrice":46},
    {"brand":"Orange","sellerRef":"Wikivu","quantity":19,"unitPrice":48},
    {"brand":"TOPIRAMATE","sellerRef":"Meevee","quantity":88,"unitPrice":13},
    {"brand":"Norvasc","sellerRef":"Mynte","quantity":55,"unitPrice":57},
    {"brand":"Valtrum US Aerobic Sport IMMEDIATE ACTION","sellerRef":"Feedmix","quantity":44,"unitPrice":19},
    {"brand":"Senna/Docusate Sodium","sellerRef":"Mycat","quantity":61,"unitPrice":30},
    {"brand":"Solar Sense Zany Zinc SPF 50 - Pink","sellerRef":"Photofeed","quantity":80,"unitPrice":84},
    {"brand":"DECONEX","sellerRef":"Yacero","quantity":2,"unitPrice":69},
    {"brand":"Lidocaine 5%","sellerRef":"Vipe","quantity":6,"unitPrice":95},
    {"brand":"decitabine","sellerRef":"Dynabox","quantity":8,"unitPrice":48},
    {"brand":"CREEPING BENT GRASS POLLEN","sellerRef":"Aimbu","quantity":34,"unitPrice":15},
    {"brand":"ALTAVERA","sellerRef":"Gigazoom","quantity":53,"unitPrice":72},
    {"brand":"Kids Crest Cavity Protection","sellerRef":"Wordpedia","quantity":33,"unitPrice":34},
    {"brand":"Lithium Carbonate","sellerRef":"Wordware","quantity":37,"unitPrice":62},
    {"brand":"Baclofen","sellerRef":"Browsecat","quantity":98,"unitPrice":8},
    {"brand":"Oxygen","sellerRef":"Jazzy","quantity":55,"unitPrice":58},
    {"brand":"Listerine Healthy White Anticavity Mouthrinse Gentle Clean Mint","sellerRef":"Roodel","quantity":29,"unitPrice":48},
    {"brand":"Phos-Flur Ortho Defense","sellerRef":"Browsecat","quantity":45,"unitPrice":26},
    {"brand":"Eucalyptus Sap Patch","sellerRef":"Skaboo","quantity":34,"unitPrice":21},
    {"brand":"UV Shield SPF 42","sellerRef":"Realmix","quantity":59,"unitPrice":15},
    {"brand":"Edarbyclor","sellerRef":"Meembee","quantity":67,"unitPrice":89},
    {"brand":"Flawless Finish Bare Perfection Makeup SPF 8 Mocha","sellerRef":"Oodoo","quantity":78,"unitPrice":98},
    {"brand":"triple antibiotic","sellerRef":"Browsedrive","quantity":53,"unitPrice":98},
    {"brand":"CLE DE PEAU BEAUTE CREAM COMPACT FOUNDATION","sellerRef":"Skyndu","quantity":36,"unitPrice":4},
    {"brand":"Eczema Rescue","sellerRef":"Browsedrive","quantity":73,"unitPrice":14},
    {"brand":"Clopidogrel bisulfate","sellerRef":"Kimia","quantity":79,"unitPrice":15},
    {"brand":"EcoCare 275","sellerRef":"Devshare","quantity":86,"unitPrice":14},
    {"brand":"Furosemide","sellerRef":"Centimia","quantity":99,"unitPrice":71},
    {"brand":"Medium Deep Warm Perfecting Makeup Broad Spectrum SPF 25","sellerRef":"Quatz","quantity":3,"unitPrice":85},
    {"brand":"Metoprolol Tartrate","sellerRef":"Devpulse","quantity":46,"unitPrice":22},
    {"brand":"Dronabinol","sellerRef":"Mycat","quantity":72,"unitPrice":26},
    {"brand":"ConRx Alert","sellerRef":"Realfire","quantity":4,"unitPrice":1},
    {"brand":"Stress Complex","sellerRef":"Devpulse","quantity":50,"unitPrice":25},
    {"brand":"ELCURE CUREKIN","sellerRef":"Vinder","quantity":43,"unitPrice":69},
    {"brand":"Allopurinol","sellerRef":"Roomm","quantity":93,"unitPrice":6},
    {"brand":"Buprenorphine HCl and Naloxone HCl","sellerRef":"Demivee","quantity":8,"unitPrice":60},
    {"brand":"Metoclopramide","sellerRef":"Twinte","quantity":89,"unitPrice":39},
    {"brand":"Pristall SaniShield Alcohol Free Antiseptic Hand Sanitizer","sellerRef":"Riffwire","quantity":35,"unitPrice":63},
    {"brand":"PHENERGAN","sellerRef":"Leexo","quantity":33,"unitPrice":75},
    {"brand":"Healing Waters Cucumber Mint Antibacterial Hand Soap","sellerRef":"Kwinu","quantity":39,"unitPrice":60},
    {"brand":"Esika Passion Musk Antiperspirant Roll-On Deodorant","sellerRef":"Fivechat","quantity":100,"unitPrice":23},
    {"brand":"Nifedipine","sellerRef":"Oyoloo","quantity":99,"unitPrice":19},
    {"brand":"Vincasar PFS","sellerRef":"Edgewire","quantity":98,"unitPrice":8},
    {"brand":"AGARICUS PANTHERINUS","sellerRef":"Photobug","quantity":83,"unitPrice":20},
    {"brand":"SENSAI FLUID FINISH LASTING VELVET FV103","sellerRef":"Wordpedia","quantity":9,"unitPrice":41},
    {"brand":"Age Spot Control","sellerRef":"Linkbuzz","quantity":54,"unitPrice":42},
    {"brand":"Elm Mixture","sellerRef":"Skilith","quantity":78,"unitPrice":11},
    {"brand":"Instant Hand Sanitizer","sellerRef":"Rhyzio","quantity":95,"unitPrice":82},
    {"brand":"Timeless EGF Power Toner","sellerRef":"Browsetype","quantity":48,"unitPrice":97},
    {"brand":"Dover Addaprin","sellerRef":"Flashspan","quantity":66,"unitPrice":13},
    {"brand":"Lobster","sellerRef":"Bluezoom","quantity":23,"unitPrice":74},
    {"brand":"Promethazine Hydrochloride","sellerRef":"Jaxworks","quantity":2,"unitPrice":59},
    {"brand":"BareMinerals Medium Deep matte","sellerRef":"Livefish","quantity":98,"unitPrice":79},
    {"brand":"Proactiv Solution","sellerRef":"Vitz","quantity":92,"unitPrice":20},
    {"brand":"triple antibiotic","sellerRef":"Feedfire","quantity":4,"unitPrice":82},
    {"brand":"Amlodipine besylate/atorvastatin calcium","sellerRef":"Skinder","quantity":90,"unitPrice":38},
    {"brand":"Furosemide","sellerRef":"Riffwire","quantity":87,"unitPrice":1},
    {"brand":"Cough Relief","sellerRef":"Babbleset","quantity":63,"unitPrice":31},
    {"brand":"Panama Jack","sellerRef":"Mybuzz","quantity":62,"unitPrice":39},
    {"brand":"Sleep Aid","sellerRef":"Vinte","quantity":63,"unitPrice":60}])